## 01. Resume Preprocessing

In [62]:
!pip install wordninja num2words inflect datasets

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: wordninja in c:\users\letha\appdata\roaming\python\python310\site-packages (2.0.0)
Requirement already satisfied: num2words in c:\users\letha\appdata\roaming\python\python310\site-packages (0.5.14)
Requirement already satisfied: inflect in c:\users\letha\appdata\roaming\python\python310\site-packages (7.5.0)
Requirement already satisfied: datasets in c:\users\letha\appdata\roaming\python\python310\site-packages (4.5.0)
Requirement already satisfied: docopt>=0.6.2 in c:\users\letha\appdata\roaming\python\python310\site-packages (from num2words) (0.6.2)
Requirement already satisfied: more_itertools>=8.5.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from inflect) (10.8.0)
Requirement already satisfied: typeguard>=4.0.1 in c:\users\letha\appdata\roaming\python\python310\site-packages (from inflect) (4.4.4)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (4.67.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (0.36.0)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (22.0.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (6.0.3)
Requirement already satisfied: filelock in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (3.20.3)
Requirement already satisfied: numpy>=1.17 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (2.2.6)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (0.4.0)
Requirement already satisfied: xxhash in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (3.6.0)
Requirement already satisfied: httpx<1.0.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (0.28.1)
Requirement already satisfied: packaging in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (25.0)
Requirement already satisfied: pandas in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (2.32.5)
Requirement already satisfied: fsspec[http]<=2025.10.0,>=2023.1.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (2025.10.0)
Requirement already satisfied: multiprocess<0.70.19 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (0.70.18)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\letha\appdata\roaming\python\python310\site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: idna in c:\users\letha\appdata\roaming\python\python310\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: httpcore==1.* in c:\users\letha\appdata\roaming\python\python310\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: anyio in c:\users\letha\appdata\roaming\python\python310\site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in c:\users\letha\appdata\roaming\python\python310\site-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: h11>=0.16 in c:\users\letha\appdata\roaming\python\python310\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\letha\appdata\roaming\python\python310\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\letha\appdata\roaming\python\python310\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\letha\appdata\roaming\python\python310\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: colorama in c:\users\letha\appdata\roaming\python\python310\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: pytz>=2020.1 in c:\users\letha\appdata\roaming\python\python310\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\letha\appdata\roaming\python\python310\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\letha\appdata\roaming\python\python310\site-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\letha\appdata\roaming\python\python310\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\letha\appdata\roaming\python\python310\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: async-timeout<6.0,>=4.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (5.0.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: six>=1.5 in c:\users\letha\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\letha\appdata\roaming\python\python310\site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)

[notice] A new release of pip is available: 23.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [63]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import wordninja
from num2words import num2words
import inflect
from datasets import load_dataset
from collections import Counter
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import spacy

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('punkt_tab')
p = inflect.engine()
nlp = spacy.load("en_core_web_sm")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\letha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\letha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\letha\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\letha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\letha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [64]:
df = pd.read_csv("C:\code\project-ky8\Data-mining\data_mining\ResumeDataSet.csv")
df.head(20)

        Category                                             Resume
0   Data Science  Skills * Programming Languages: Python (pandas...
1   Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2   Data Science  Areas of Interest Deep Learning, Control Syste...
3   Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4   Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...
5   Data Science  SKILLS C Basics, IOT, Python, MATLAB, Data Sci...
6   Data Science  Skills â¢ Python â¢ Tableau â¢ Data Visuali...
7   Data Science  Education Details \r\n B.Tech   Rayat and Bahr...
8   Data Science  Personal Skills â¢ Ability to quickly grasp t...
9   Data Science  Expertise â Data and Quantitative Analysis â...
10  Data Science  Skills * Programming Languages: Python (pandas...
11  Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
12  Data Science  Areas of Interest Deep Learning, Control Syste...
13  Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
14  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...
15  Data Science  SKILLS C Basics, IOT, Python, MATLAB, Data Sci...
16  Data Science  Skills â¢ Python â¢ Tableau â¢ Data Visuali...
17  Data Science  Education Details \r\n B.Tech   Rayat and Bahr...
18  Data Science  Personal Skills â¢ Ability to quickly grasp t...
19  Data Science  Expertise â Data and Quantitative Analysis â...

In [65]:
df.shape

(962, 2)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 962 entries, 0 to 961
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  962 non-null    object
 1   Resume    962 non-null    object
dtypes: object(2)
memory usage: 15.2+ KB

In [67]:
df = df.drop_duplicates(subset=['Resume'], keep='first')

In [68]:
def preprocessing_data(text, idx):
    text = text.lower()
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE) # remove link
    text = re.sub(r'\b(?:https?://)?(?:www\.)?[a-zA-Z0-9-]+\.(?:com|org|net|edu|gov|co|co\.id|info|biz|us|ca|uk|de|jp)\S*\s*', '', text) # remove link
    text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', '', text) # remove email
    text = re.sub(r'\+?\d[\d -]{8,}\d', '', text) # remove phone number
    text = re.sub(r'\b\d{1,4}[/-]\d{1,2}[/-]\d{1,4}\b', '', text) # remove date -> 01/12/2000
    text = re.sub(r'\b[A-Za-z]+\s\d{4}\b', '', text) # remove date -> May 2013
    text = re.sub(r'[^\w\s]', ' ', text) # punctuation
    text = text.replace("exprience", "experience")
    text = text.replace("matelabs", "matlab")
    text = text.replace("maharashtra", " ")
    text = text.replace("monthscompany", " ")
    text = text.replace("-", " ")

    # convert number to word with the following requirement
    pattern = r'\b(\d+)\s+(year|years|months|month|experience|position|skill)\b'

    def replace_match(match):
        number = match.group(1)
        word = p.number_to_words(number)
        return f"{word} {match.group(2)}"

    # Gantikan angka relevan dengan kata
    text = re.sub(pattern, replace_match, text, flags=re.IGNORECASE)

    # Hapus angka yang tidak relevan
    text = re.sub(r'\b\d+\b', '', text)
    text = re.sub(r'\b\w\b', '', text) # remove single character
    text = re.sub(r'[^\w\s]', ' ', text) # punctuation

    # remove stopword and lemmatization
    stop_words = set(stopwords.words('english'))
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]

    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    text = ' '.join(tokens)

    # remove word that related to location
    doc = nlp(text)
    tokens = [token.text for token in doc if token.ent_type_ != 'GPE']
    text = ' '.join(tokens)

    # # remove verb
    # doc = nlp(text)
    # non_verbs = [token.text for token in doc if token.pos_ not in ["VERB"]]
    # text = ' '.join(non_verbs)

    print(f"Index: {idx}, Preprocessed Text : {' '.join(tokens[:5])}")
    return text

In [69]:
df['clean_data'] = df.apply(lambda row: preprocessing_data(row['Resume'], row.name), axis=1)

Index: 0, Preprocessed Text : skill programming language python panda
Index: 1, Preprocessed Text : education detail uit rgpv data
Index: 2, Preprocessed Text : area interest deep learning control
Index: 3, Preprocessed Text : skill python sap hana tableau
Index: 4, Preprocessed Text : education detail mca ymcaust faridabad
Index: 5, Preprocessed Text : skill basic iot python matlab
Index: 6, Preprocessed Text : skill python tableau data visualization
Index: 7, Preprocessed Text : education detail tech rayat bahra
Index: 8, Preprocessed Text : personal skill ability quickly grasp
Index: 9, Preprocessed Text : expertise data quantitative analysis decision
Index: 40, Preprocessed Text : technical skill typewriting tora spsseducation
Index: 41, Preprocessed Text : skill window xp m office
Index: 42, Preprocessed Text : education detail ba mumbai university
Index: 43, Preprocessed Text : education detail economics chennai tamil
Index: 45, Preprocessed Text : education detail bba lovely professional
Index: 46, Preprocessed Text : education detail mba acn college
Index: 47, Preprocessed Text : key skill computerized accounting tally
Index: 48, Preprocessed Text : training special education certificate course
Index: 49, Preprocessed Text : computer knowledge proficient basic use
Index: 50, Preprocessed Text : software skill general computer proficiency
Index: 84, Preprocessed Text : technical qualification window m officeeducation
Index: 85, Preprocessed Text : education detail university clacutta university
Index: 86, Preprocessed Text : education detail llb dibrugarh university
Index: 87, Preprocessed Text : education detail llm master law
Index: 88, Preprocessed Text : skill know english native speaker
Index: 89, Preprocessed Text : qualification introduction computer extraeducation detail
Index: 90, Preprocessed Text : skill natural language proficient english
Index: 91, Preprocessed Text : skill legal writing efficient researcher
Index: 92, Preprocessed Text : good grasping quality skillful work
Index: 93, Preprocessed Text : hard working quick learnereducation detail
Index: 104, Preprocessed Text : good communication skill quick learner
Index: 105, Preprocessed Text : operating system window xp vista
Index: 106, Preprocessed Text : additional qualification web designing course
Index: 107, Preprocessed Text : education detail rachana sansad school
Index: 108, Preprocessed Text : education detail entermediate math mumbai
Index: 109, Preprocessed Text : skill course skill name board
Index: 140, Preprocessed Text : technical skill web technology angular
Index: 141, Preprocessed Text : education detail bachelor computer application
Index: 143, Preprocessed Text : education detail sc information technology
Index: 144, Preprocessed Text : skill language basic java basic
Index: 185, Preprocessed Text : education detail diploma mechanical engg
Index: 186, Preprocessed Text : skill knowledge software computer auto
Index: 187, Preprocessed Text : education detail bachelor engineering engineering
Index: 188, Preprocessed Text : education detail mechanical engineering pune
Index: 189, Preprocessed Text : hard working person self confident
Index: 225, Preprocessed Text : education detail bachelor bachelor commerce
Index: 226, Preprocessed Text : skill m office good communication
Index: 227, Preprocessed Text : key skill planning strategizing presentation
Index: 228, Preprocessed Text : skill m office photoshop sql
Index: 229, Preprocessed Text : skill set multi tasking collaborative
Index: 265, Preprocessed Text : education detail first year science
Index: 266, Preprocessed Text : education detail nutrition exercise physiology
Index: 267, Preprocessed Text : personal skill good verbal written
Index: 268, Preprocessed Text : skill computer easily operate operating
Index: 269, Preprocessed Text : education detail sport science dr
Index: 270, Preprocessed Text : education detail diploma nutrition education
Index: 295, Preprocessed Text : education detail civil engineering civil
Index: 296, Preprocessed Text : education detail baramati highschool civil
Index: 297, Preprocessed Text : skill autocad pro word excel
Index: 298, Preprocessed Text : computer skill holder valid ksa
Index: 299, Preprocessed Text : computer knowledge drafting tool autocad
Index: 300, Preprocessed Text : personal skill passionate towards learning
Index: 319, Preprocessed Text : education detail electronics communication jabalpur
Index: 320, Preprocessed Text : technical skill trained project acquired
Index: 321, Preprocessed Text : technical skill skill java sql
Index: 322, Preprocessed Text : technical strength computer language java
Index: 323, Preprocessed Text : education detail master engineering information
Index: 324, Preprocessed Text : education detail pjlce java developer
Index: 325, Preprocessed Text : technicalskills springmvc hibernate jdbc java
Index: 327, Preprocessed Text : operating system window xp tool
Index: 328, Preprocessed Text : computer skill language script jsp
Index: 329, Preprocessed Text : education detail information technology pune
Index: 330, Preprocessed Text : technical skill programming language java
Index: 331, Preprocessed Text : skill team leading self motivated
Index: 332, Preprocessed Text : skill language java operating system
Index: 403, Preprocessed Text : education detail computer science mumbai
Index: 404, Preprocessed Text : technical skill application server ii
Index: 405, Preprocessed Text : key skill requirement gathering requirement
Index: 406, Preprocessed Text : skill area exposure modeling tool
Index: 407, Preprocessed Text : technological skill knowledge computer window
Index: 408, Preprocessed Text : education detail tybcom commerce mumbai
Index: 431, Preprocessed Text : skill etl data warehousing sql
Index: 432, Preprocessed Text : competency sap business intelligence version
Index: 433, Preprocessed Text : education detail computer science nagpur
Index: 434, Preprocessed Text : education detail master computer application
Index: 435, Preprocessed Text : education detail bachelor engineering lean
Index: 436, Preprocessed Text : education detail sap technical architect
Index: 455, Preprocessed Text : excellent grasping power learning new
Index: 456, Preprocessed Text : social skill ability establish trust
Index: 457, Preprocessed Text : technical skill automation testing selenium
Index: 458, Preprocessed Text : skill agile methodology scrum kanban
Index: 459, Preprocessed Text : technical skill summary completed corporate
Index: 460, Preprocessed Text : education detail tech electronics instrumentation
Index: 461, Preprocessed Text : technical skill language core java
Index: 481, Preprocessed Text : skill mc office introductory knowledge
Index: 482, Preprocessed Text : education detail electrical engineering skill
Index: 483, Preprocessed Text : achievement oriented people management skill
Index: 484, Preprocessed Text : education detail electrical electronics engineering
Index: 485, Preprocessed Text : education detail electrical shivaji university
Index: 511, Preprocessed Text : education detail bca vinayaka mission
Index: 512, Preprocessed Text : key competency multi operation managementâ
Index: 513, Preprocessed Text : skill well versed m office
Index: 514, Preprocessed Text : education detail electronics pune pune
Index: 551, Preprocessed Text : technical skill responsibility hand experience
Index: 552, Preprocessed Text : education detail diploma computer science
Index: 553, Preprocessed Text : technical proficiency platform ubuntu fedora
Index: 554, Preprocessed Text : technical skill language python python
Index: 555, Preprocessed Text : training attended successfully completed esd
Index: 556, Preprocessed Text : operating system window others m
Index: 599, Preprocessed Text : skill visa b1 visa usa
Index: 600, Preprocessed Text : software proficiency language basic sql
Index: 601, Preprocessed Text : core competency ant maven git
Index: 602, Preprocessed Text : technical skill key skill m
Index: 603, Preprocessed Text : core skill project program management
Index: 604, Preprocessed Text : total experience fifteen year core
Index: 605, Preprocessed Text : technical skill hp alm rtc
Index: 654, Preprocessed Text : skill set experience implementing troubleshooting
Index: 655, Preprocessed Text : skill set cisco certified network
Index: 656, Preprocessed Text : communication skill writing skill english
Index: 657, Preprocessed Text : technical expertise cisco asa checkpoint
Index: 658, Preprocessed Text : operating system window linux ubuntu
Index: 679, Preprocessed Text : core competency maintain process ensure
Index: 680, Preprocessed Text : area expertise profile around plus
Index: 681, Preprocessed Text : skill exceptional communication networking skill
Index: 709, Preprocessed Text : technical expertise db language sql
Index: 710, Preprocessed Text : technical expertise operating system microsoft
Index: 711, Preprocessed Text : technical skill operating system m
Index: 712, Preprocessed Text : skillset oracle dba mysql mariadb
Index: 713, Preprocessed Text : education detail bsc mumbai mumbai
Index: 714, Preprocessed Text : technical skill operating system linux
Index: 715, Preprocessed Text : technical skill database oracle rdbms
Index: 716, Preprocessed Text : software skill rdbms m sql
Index: 717, Preprocessed Text : area expertise oracle database 12c
Index: 718, Preprocessed Text : education detail bachelor science information
Index: 719, Preprocessed Text : technical skill sql oracle v10
Index: 742, Preprocessed Text : education detail hadoop developer hadoop
Index: 743, Preprocessed Text : skill set hadoop map reduce
Index: 744, Preprocessed Text : operating system linux ubuntu tool
Index: 745, Preprocessed Text : area expertise big data ecosystem
Index: 746, Preprocessed Text : technical skill set programming language
Index: 747, Preprocessed Text : technical skill programming language java
Index: 748, Preprocessed Text : technical skill set big data
Index: 784, Preprocessed Text : technical summary knowledge informatica power
Index: 785, Preprocessed Text : technicalproficiencies db oracle 11 g
Index: 786, Preprocessed Text : education detail bachelor engineering extc
Index: 787, Preprocessed Text : skill set talend big data
Index: 788, Preprocessed Text : computer skill yes sql knowledge
Index: 824, Preprocessed Text : technical skill web technology asp
Index: 825, Preprocessed Text : participated intra college cricket competition
Index: 826, Preprocessed Text : technical skill language asp net
Index: 827, Preprocessed Text : education detail education detail pune
Index: 828, Preprocessed Text : technology mvc unit testing entity
Index: 829, Preprocessed Text : technical skill category skill language
Index: 830, Preprocessed Text : technical skill programming language net
Index: 852, Preprocessed Text : hobby playing chess solving rubik
Index: 853, Preprocessed Text : skill strong c fundamental problem
Index: 854, Preprocessed Text : key skill programing language python
Index: 855, Preprocessed Text : software skill language java operating
Index: 856, Preprocessed Text : skill bitcoin ethereum solidity hyperledger
Index: 892, Preprocessed Text : good logical analytical skill positive
Index: 893, Preprocessed Text : computer proficiency basic m office
Index: 894, Preprocessed Text : computer skill proficient m office
Index: 895, Preprocessed Text : willingness accept challenge positive thinking
Index: 896, Preprocessed Text : personal skill quick learner eagerness
Index: 897, Preprocessed Text : computer skill software knowledge m
Index: 898, Preprocessed Text : skill set o window xp

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 166 entries, 0 to 898
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Category    166 non-null    object
 1   Resume      166 non-null    object
 2   clean_data  166 non-null    object
dtypes: object(3)
memory usage: 5.2+ KB

In [71]:
df['text_length'] = df['clean_data'].apply(lambda x: len(x.split()))
print(df['text_length'].describe())

count     166.000000
mean      295.222892
std       257.114510
min        14.000000
25%       108.000000
50%       229.500000
75%       405.000000
max      1422.000000
Name: text_length, dtype: float64

In [72]:
df[df['text_length'] > 405].count()

Category       42
Resume         42
clean_data     42
text_length    42
dtype: int64

In [73]:
all_words = ' '.join(df['clean_data']).split()
word_freq = Counter(all_words)
# print(word_freq.most_common()[-1000:-5000:-1])
# print(word_freq.most_common(100))

In [74]:
# Tentukan ambang batas untuk menghapus kata-kata yang jarang muncul
# Misalnya, kita akan menghapus kata-kata yang muncul kurang dari 2 kali
threshold = 2
rare_words = [word for word, freq in word_freq.items() if freq <= threshold]

# Fungsi untuk menghapus kata-kata yang jarang muncul dari teks
def remove_rare_words(text, rare_words):
    return ' '.join([word for word in text.split() if word not in rare_words])

# Terapkan fungsi ini ke setiap teks dalam data
cleaned_texts = [remove_rare_words(text, rare_words) for text in df['clean_data']]
df = pd.DataFrame(cleaned_texts, columns=['clean_data'])

In [75]:
df['text_length'] = df['clean_data'].apply(lambda x: len(x.split()))
print(df['text_length'].describe())

count     166.000000
mean      265.283133
std       235.009242
min        12.000000
25%        90.000000
50%       194.500000
75%       363.250000
max      1292.000000
Name: text_length, dtype: float64

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   clean_data   166 non-null    object
 1   text_length  166 non-null    int64
dtypes: int64(1), object(1)
memory usage: 2.7+ KB

In [77]:
df.to_csv('C:\code\project-ky8\Data-mining\data_mining\dataset_resume.csv', index=False)

# Hugging Face Resume Job : https://huggingface.co/datasets/cnamuangtoun/resume-job-description-fit

In [78]:
!pip install datasets
from datasets import load_dataset
import pandas as pd

ds = load_dataset("cnamuangtoun/resume-job-description-fit")

df_train = pd.DataFrame(ds['train'])
df_test = pd.DataFrame(ds['test'])

df_train = df_train.drop(columns=['label'])
df_test = df_test.drop(columns=['label'])

df_cv = pd.concat([df_train['resume_text'], df_test['resume_text']], ignore_index=True)
df_jd = pd.concat([df_train['job_description_text'], df_test['job_description_text']], ignore_index=True)

[notice] A new release of pip is available: 23.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: datasets in c:\users\letha\appdata\roaming\python\python310\site-packages (4.5.0)
Requirement already satisfied: numpy>=1.17 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (2.2.6)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (22.0.0)
Requirement already satisfied: requests>=2.32.2 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (2.32.5)
Requirement already satisfied: fsspec[http]<=2025.10.0,>=2023.1.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (2025.10.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (6.0.3)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (0.4.0)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (4.67.1)
Requirement already satisfied: pandas in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (2.3.3)
Requirement already satisfied: xxhash in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (3.6.0)
Requirement already satisfied: httpx<1.0.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (0.28.1)
Requirement already satisfied: multiprocess<0.70.19 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (0.70.18)
Requirement already satisfied: filelock in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (3.20.3)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (0.36.0)
Requirement already satisfied: packaging in c:\users\letha\appdata\roaming\python\python310\site-packages (from datasets) (25.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\letha\appdata\roaming\python\python310\site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in c:\users\letha\appdata\roaming\python\python310\site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: idna in c:\users\letha\appdata\roaming\python\python310\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: httpcore==1.* in c:\users\letha\appdata\roaming\python\python310\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: certifi in c:\users\letha\appdata\roaming\python\python310\site-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: h11>=0.16 in c:\users\letha\appdata\roaming\python\python310\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\letha\appdata\roaming\python\python310\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\letha\appdata\roaming\python\python310\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\letha\appdata\roaming\python\python310\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: colorama in c:\users\letha\appdata\roaming\python\python310\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\letha\appdata\roaming\python\python310\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\letha\appdata\roaming\python\python310\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\letha\appdata\roaming\python\python310\site-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\letha\appdata\roaming\python\python310\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\letha\appdata\roaming\python\python310\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: async-timeout<6.0,>=4.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\letha\appdata\roaming\python\python310\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: six>=1.5 in c:\users\letha\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\letha\appdata\roaming\python\python310\site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)

In [79]:
df_cv.info()

<class 'pandas.core.series.Series'>
RangeIndex: 8000 entries, 0 to 7999
Series name: resume_text
Non-Null Count  Dtype
--------------  -----
8000 non-null   object
dtypes: object(1)
memory usage: 62.6+ KB

In [80]:
train_duplicates = df_cv[df_cv.duplicated()].count()
print(train_duplicates)

7357

In [81]:
df_cv = df_cv.drop_duplicates(keep='first')

In [82]:
df_cv.info()

<class 'pandas.core.series.Series'>
Index: 643 entries, 0 to 6277
Series name: resume_text
Non-Null Count  Dtype
--------------  -----
643 non-null    object
dtypes: object(1)
memory usage: 10.0+ KB

In [83]:
def preprocessing_data1(text):
    text = text.lower()
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE) # remove link
    text = re.sub(r'\b(?:https?://)?(?:www\.)?[a-zA-Z0-9-]+\.(?:com|org|net|edu|gov|co|co\.id|info|biz|us|ca|uk|de|jp)\S*\s*', '', text) # remove link
    text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', '', text) # remove email
    text = re.sub(r'\+?\d[\d -]{8,}\d', '', text) # remove phone number
    text = re.sub(r'\b\d{1,4}[/-]\d{1,2}[/-]\d{1,4}\b', '', text) # remove date -> 01/12/2000
    text = re.sub(r'\b[A-Za-z]+\s\d{4}\b', '', text) # remove date -> May 2013
    text = re.sub(r'[^\w\s]', ' ', text) # punctuation

    # convert number to word with the following requirement
    pattern = r'\b(\d+)\s+(year|years|months|month|experience|position|skill)\b'

    def replace_match(match):
        number = match.group(1)
        word = p.number_to_words(number)
        return f"{word} {match.group(2)}"

    # Gantikan angka relevan dengan kata
    text = re.sub(pattern, replace_match, text, flags=re.IGNORECASE)

    # Hapus angka yang tidak relevan
    text = re.sub(r'\b\d+\b', '', text)
    text = re.sub(r'\b\w\b', '', text) # remove single character

    # remove stopword and lemmatization
    stop_words = set(stopwords.words('english'))
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]

    preprocessed_text = ' '.join(tokens)
    # print(f"Index: {idx}, Preprocessed Text : {' '.join(tokens[:5])}")
    return preprocessed_text

# Hugging Face Resume Job : https://huggingface.co/datasets/InferencePrince555/Resume-Dataset?row=0

In [84]:
ds1 = load_dataset("InferencePrince555/Resume-Dataset")
df_cv1 = pd.DataFrame(ds1['train'])
df_cv1 = df_cv1.drop(columns=['input'])
df_cv1.head(20)

,instruction,Resume_test
0,Generate a Resume for a Accountant Job,ACCOUNTANT Professional Summary Results orient...
1,Generate a Resume for a Accountant Job,STAFF ACCOUNTANT Summary Flexible Accountant w...
2,Generate a Resume for a Accountant Job,STAFF ACCOUNTANT Summary Highly analytical and...
3,Generate a Resume for a Accountant Job,SENIOR ACCOUNTANT Summary A highly competent m...
4,Generate a Resume for a Accountant Job,SENIOR ACCOUNTANT Summary 11 years experience ...
5,Generate a Resume for a Accountant Job,FINANCIAL ACCOUNTANT Summary CPA Financial Acc...
6,Generate a Resume for a Accountant Job,CORPORATE ACCOUNTANT Summary Over 15 years of ...
7,Generate a Resume for a Accountant Job,ACCOUNTANT Professional Summary Current Accoun...
8,Generate a Resume for a Accountant Job,ACCOUNTANT Summary Innovative and energetic Ac...
9,Generate a Resume for a Accountant Job,ACCOUNTANT Highlights Microsoft Office Interme...
10,Generate a Resume for a Accountant Job,STAFF ACCOUNTANT Professional Profile To gain ...
11,Generate a Resume for a Accountant Job,ACCOUNTANT II Professional Summary Highly anal...
12,Generate a Resume for a Accountant Job,ACCOUNTANT Summary To pursue excellence in the...
13,Generate a Resume for a Accountant Job,PROJECT ACCOUNTANT Career Focus Dedicated and ...
14,Generate a Resume for a Accountant Job,CONTRACT ACCOUNTANT Summary More than ten year...
15,Generate a Resume for a Accountant Job,SENIOR ACCOUNTANT Professional Summary Senior ...
16,Generate a Resume for a Accountant Job,PROJECT ACCOUNTANT Summary Quality focused acc...
17,Generate a Resume for a Accountant Job,ACCOUNTANT I Summary Flexible A ccountant who ...
18,Generate a Resume for a Accountant Job,ACCOUNTANT Summary To utilize my customer rela...
19,Generate a Resume for a Accountant Job,SUPERVISOR ACCOUNTANT Professional Summary Abi...

In [85]:
train_duplicates = df_cv1[df_cv1['Resume_test'].duplicated()].count()
print(train_duplicates)

instruction    818
Resume_test    818
dtype: int64

In [86]:
df_cv1 = df_cv1.drop_duplicates(keep='first')
df_cv1 = df_cv1.dropna(subset=['Resume_test'])

In [87]:
def preprocess_job_title(text):
    cleaned_text = re.sub(r'Generate a Resume for a\s+|\s+Job', '', text, flags=re.IGNORECASE)

    cleaned_text = cleaned_text.lower()

    return cleaned_text

In [88]:
import re
df_cv1['category'] = df_cv1['instruction'].apply(preprocess_job_title)

In [89]:
def preprocess_job_title(text):
    cleaned_text = re.sub(r'Generate a Resume for a\s+|\s+Job', '', text, flags=re.IGNORECASE)

    cleaned_text = cleaned_text.lower()

    return cleaned_text

In [90]:
df_cv1 = df_cv1.drop(columns=['instruction'])
df_cv1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31680 entries, 0 to 32480
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Resume_test  31680 non-null  object
 1   category     31680 non-null  object
dtypes: object(2)
memory usage: 742.5+ KB

In [91]:
df_cv1['category'] = df_cv1['category'].replace('web designing', 'UI/UX Designer')
df_cv1['category'] = df_cv1['category'].replace('database', 'database administrator')

In [92]:
df_cv1['category'].value_counts()

category
software developer           5827
systems administrator        4181
project manager              3527
web developer                3466
database administrator       2795
java developer               2431
python developer             2317
network administrator        2260
security analyst             2259
advocate                      128
sales                         121
hr                            120
information technology        120
business development          119
chef                          118
engineering                   118
accountant                    118
finance                       117
fitness                       117
aviation                      116
consultant                    115
healthcare                    115
banking                       115
construction                  112
public relations              111
arts                          109
designer                      107
teacher                       102
apparel                        97
digital media                  96
agriculture                    63
automobile                     36
bpo                            22
data science                   10
automation testing              7
dotnet developer                7
devops engineer                 7
hadoop                          7
testing                         7
sap developer                   6
business analyst                6
civil engineer                  6
health and fitness              6
blockchain                      5
mechanical engineer             5
electrical engineering          5
etl developer                   5
network security engineer       5
operations manager              4
UI/UX Designer                  4
pmo                             3
Name: count, dtype: int64

In [93]:
def preprocessing_data1(text, idx):
    text = text.lower()
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE) # remove link
    text = re.sub(r'\b(?:https?://)?(?:www\.)?[a-zA-Z0-9-]+\.(?:com|org|net|edu|gov|co|co\.id|info|biz|us|ca|uk|de|jp)\S*\s*', '', text) # remove link
    text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', '', text) # remove email
    text = re.sub(r'\+?\d[\d -]{8,}\d', '', text) # remove phone number
    text = re.sub(r'\b\d{1,4}[/-]\d{1,2}[/-]\d{1,4}\b', '', text) # remove date -> 01/12/2000
    text = re.sub(r'\b[A-Za-z]+\s\d{4}\b', '', text) # remove date -> May 2013
    text = re.sub(r'[^\w\s]', ' ', text) # punctuation

    # remove text from this pattern
    pattern = r'.*?\bsummary\b'
    text = re.sub(pattern, '', text, flags=re.IGNORECASE)

    # convert number to word with the following requirement
    pattern = r'\b(\d+)\s+(year|years|months|month|experience|position|skill)\b'

    def replace_match(match):
        number = match.group(1)
        word = p.number_to_words(number)
        return f"{word} {match.group(2)}"

    # Gantikan angka relevan dengan kata
    text = re.sub(pattern, replace_match, text, flags=re.IGNORECASE)

    # Hapus angka yang tidak relevan
    text = re.sub(r'\b\d+\b', '', text)
    text = re.sub(r'\b\w\b', '', text) # remove single character
    text = re.sub(r'[^\w\s]', ' ', text) # punctuation

    # remove stopword and lemmatization
    stop_words = set(stopwords.words('english'))
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]

    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    text = ' '.join(tokens)

    # # remove word that related to location, date, and cardinal
    # doc = nlp(text)
    # tokens = [token.text for token in doc if token.ent_type_ != 'GPE' and token.ent_type_ != 'DATE' and token.ent_type_ != 'CARDINAL' ]
    # text = ' '.join(tokens)

    # # remove verb
    # doc = nlp(text)
    # non_verbs = [token.text for token in doc if token.pos_ not in ["VERB"]]
    # text = ' '.join(non_verbs)

    print(f"Index: {idx}, Preprocessed Text : {' '.join(tokens[:5])}")
    return text

In [94]:
import inflect
from nltk.corpus import stopwords

p = inflect.engine()

df_cv1['clean_data'] = df_cv1.apply(lambda row: preprocessing_data1(row['Resume_test'], row.name), axis=1)

Index: 0, Preprocessed Text : result oriented organized bilingual accounting
Index: 1, Preprocessed Text : flexible accountant adapts seamlessly constantly
Index: 2, Preprocessed Text : highly analytical detail oriented professional
Index: 3, Preprocessed Text : analysis prepare auction sale journal
Index: 4, Preprocessed Text : eleven year experience accounting profession
Index: 5, Preprocessed Text : tool monitor usage minimum guarantee
Index: 6, Preprocessed Text : fifteen year increasingly responsible experience
Index: 7, Preprocessed Text : current accountant city alexandria fifteen
Index: 8, Preprocessed Text : innovative energetic accountant proficient extracting
Index: 9, Preprocessed Text : accountant highlight microsoft office intermediate
Index: 10, Preprocessed Text : staff accountant professional profile gain
Index: 11, Preprocessed Text : highly analytical result driven tax
Index: 12, Preprocessed Text : pursue excellence dynamic business world
Index: 13, Preprocessed Text : project accountant career focus dedicated
Index: 14, Preprocessed Text : ten year progressive experience manufacturing
Index: 15, Preprocessed Text : senior accountant completes accounting activity
Index: 16, Preprocessed Text : report verification approval researched resolved
Index: 17, Preprocessed Text : flexible ccountant adapts seamlessly constantly
Index: 18, Preprocessed Text : utilize customer relation management background
Index: 19, Preprocessed Text : variance explanation senior financial analyst
Index: 20, Preprocessed Text : staff accountant experience current company
Index: 21, Preprocessed Text : flexible accountant adapts seamlessly constantly
Index: 22, Preprocessed Text : accountant eight year accounting experience
Index: 23, Preprocessed Text : financial accountant specializing financial planning
Index: 24, Preprocessed Text : financial accountant specializing financial planning
Index: 25, Preprocessed Text : capable accountant successful managing multiple
Index: 26, Preprocessed Text : strategic analytical finance professional twenty
Index: 27, Preprocessed Text : several year experience providing information
Index: 28, Preprocessed Text : talented accountant employing creative teaching
Index: 29, Preprocessed Text : sixteen year experienced professional accounting
Index: 30, Preprocessed Text : senior accountant experience company name
Index: 31, Preprocessed Text : cpa candidate fifteen year strong
Index: 32, Preprocessed Text : experienced senior corporate accountant dedicated
Index: 33, Preprocessed Text : well qualified detail oriented accounting
Index: 34, Preprocessed Text : skill internet microsoft office m
Index: 35, Preprocessed Text : senior accounting professional extensive experience
Index: 36, Preprocessed Text : seasoned professional proven ability perform
Index: 37, Preprocessed Text : accountant iii senior accountant result
Index: 38, Preprocessed Text : employee vendor data prepared daily
Index: 39, Preprocessed Text : 403b garnishment deduction payment handled
Index: 40, Preprocessed Text : financial accounting professional expertise financial
Index: 41, Preprocessed Text : detail oriented accountant five year
Index: 42, Preprocessed Text : statement brief flowchart document ensured
Index: 43, Preprocessed Text : currently graduate student master science
Index: 44, Preprocessed Text : capable accountant successful managing multiple
Index: 45, Preprocessed Text : professional accountant bookkeeper twelve year
Index: 46, Preprocessed Text : professional accountant ten year full
Index: 47, Preprocessed Text : staff accountant skill income statement
Index: 48, Preprocessed Text : capable accountant successful managing multiple
Index: 49, Preprocessed Text : experienced highly motivated work ethic
Index: 50, Preprocessed Text : acca finalist qualified diploma accountancy
Index: 51, Preprocessed Text : accomplished accountant highly skilled controller
Index: 52, Preprocessed Text : general accountant career focus obtain
Index: 53, Preprocessed Text : team oriented accountant successful managing
Index: 54, Preprocessed Text : around six year experience field
Index: 55, Preprocessed Text : report verification approval researched resolved
Index: 56, Preprocessed Text : obtain position professional organization apply
Index: 57, Preprocessed Text : capable accountant successful managing multiple
Index: 58, Preprocessed Text : accountant highlight soft skill public
Index: 59, Preprocessed Text : inpatient outpatient record coding specialist
Index: 60, Preprocessed Text : bookkeeper strong technical proficiency commitment
Index: 61, Preprocessed Text : enthusiastic knowledgeable professional experience proven
Index: 62, Preprocessed Text : result driven award winning accounting
Index: 63, Preprocessed Text : fifteen year experience account receivable
Index: 64, Preprocessed Text : financial accountant specializing financial planning
Index: 65, Preprocessed Text : general accounting procedure account payable
Index: 66, Preprocessed Text : accountant professional profile certified accountant
Index: 67, Preprocessed Text : reliable customer service representative extensive
Index: 68, Preprocessed Text : currently looking long term permanent
Index: 69, Preprocessed Text : accountant skill timberline mri yardi
Index: 70, Preprocessed Text : financial accountant specializing financial planning
Index: 71, Preprocessed Text : result oriented accountant strong work
Index: 72, Preprocessed Text : emerging accounting professional ready develop
Index: 73, Preprocessed Text : motivated sale professional ten year
Index: 74, Preprocessed Text : enthusiastic honest dedicated professional individual
Index: 75, Preprocessed Text : analysis bsa inter company reinsurance
Index: 76, Preprocessed Text : flexible bookkeeper accountant adapts seamlessly
Index: 77, Preprocessed Text : innovative accountant proficient extracting financial
Index: 78, Preprocessed Text : experienced detail oriented accountant effectively
Index: 79, Preprocessed Text : accountant medium sized company experience
Index: 80, Preprocessed Text : self motivated accountant offering strong
Index: 81, Preprocessed Text : microsoft window medium download install
Index: 82, Preprocessed Text : accountant skill quickbooks sage lacerte
Index: 83, Preprocessed Text : senior level finance management professional
Index: 84, Preprocessed Text : accountant interest buffalo creek golf
Index: 85, Preprocessed Text : funding increase productivity fifteen percent
Index: 86, Preprocessed Text : accounting professional twenty year experience
Index: 87, Preprocessed Text : accountant decade diverse professional experience
Index: 88, Preprocessed Text : worksheet prepared weekly fr2900 regulation
Index: 89, Preprocessed Text : creative active prove ability manage
Index: 90, Preprocessed Text : need someone delivers sharp result
Index: 91, Preprocessed Text : skilled accountant successful managing multiple
Index: 92, Preprocessed Text : staff accountant professional profile advance
Index: 93, Preprocessed Text : motivated enthusiastic cheerful seeking position
Index: 94, Preprocessed Text : professional accountant outstanding work ethic
Index: 95, Preprocessed Text : pursue challenging reward career allow
Index: 96, Preprocessed Text : client focused sale representative eight
Index: 97, Preprocessed Text : accountant highlight technical skill netsuite
Index: 98, Preprocessed Text : self motivated accountant offering strong
Index: 99, Preprocessed Text : talented senior accountant highly effective
Index: 100, Preprocessed Text : degreed accountant ten year diversified
Index: 101, Preprocessed Text : multi faceted financial professional solid
Index: 102, Preprocessed Text : energetic mother ten year experience
Index: 103, Preprocessed Text : obtain challenging rewarding accounting position
Index: 104, Preprocessed Text : reconciled builder proceeds mortgage proceeds
Index: 105, Preprocessed Text : highly motivated hardworking college graduate
Index: 106, Preprocessed Text : seeking position accountant utilizing knowledge
Index: 107, Preprocessed Text : skill work history current accountant
Index: 108, Preprocessed Text : obtain position fast paced business
Index: 109, Preprocessed Text : many year experience accounting finance
Index: 110, Preprocessed Text : achieve job accountant utilizes accounting
Index: 111, Preprocessed Text : bilingual accounting professional additional expertise
Index: 112, Preprocessed Text : detail oriented efficient accountant excels
Index: 113, Preprocessed Text : business management graduate significant experience
Index: 114, Preprocessed Text : eight year accomplished experience field
Index: 115, Preprocessed Text : accomplished professional exceptional skill developed
Index: 116, Preprocessed Text : detail oriented billing professional eleven
Index: 117, Preprocessed Text : personable education professional driven inspire
Index: 118, Preprocessed Text : education detail llb dibrugarh university
Index: 119, Preprocessed Text : education detail llm master law
Index: 120, Preprocessed Text : twenty nine year working industry
Index: 121, Preprocessed Text : skill natural language proficient english
Index: 122, Preprocessed Text : suit paper notice power attorney
Index: 123, Preprocessed Text : skill know english native speaker
Index: 124, Preprocessed Text : good grasping quality skillful work
Index: 125, Preprocessed Text : hard working quick learnereducation detail
Index: 126, Preprocessed Text : personal banker safe business advocate
Index: 127, Preprocessed Text : qualification introduction computer extraeducation detail
Index: 128, Preprocessed Text : experienced ten year high level
Index: 129, Preprocessed Text : talented customer service manager skilled
Index: 130, Preprocessed Text : ten year insurance industry experience
Index: 131, Preprocessed Text : adaptable friendly case worker team
Index: 132, Preprocessed Text : motivated individual exceptional customer service
Index: 133, Preprocessed Text : senior customer service advocate professional
Index: 134, Preprocessed Text : affiliation creative problem solver computer
Index: 135, Preprocessed Text : highly ambitious professional background financial
Index: 136, Preprocessed Text : highly motivated coaching analytical health
Index: 137, Preprocessed Text : patient health advocate highly motivated
Index: 138, Preprocessed Text : report company name city state
Index: 139, Preprocessed Text : administrative professional offering excellent communication
Index: 140, Preprocessed Text : dedicated focused office manager supervisor
Index: 141, Preprocessed Text : vzw customer tech advocate overview
Index: 142, Preprocessed Text : bilingual domestic violence advocate skill
Index: 143, Preprocessed Text : part organization assist offer service
Index: 144, Preprocessed Text : ph inpatient financial advocate supervisor
Index: 145, Preprocessed Text : enthusiastic hard working customer service
Index: 146, Preprocessed Text : responsible service advocate recruiter excellent
Index: 147, Preprocessed Text : management experience desire work best
Index: 148, Preprocessed Text : diversified background providing service culturally
Index: 149, Preprocessed Text : consumer service advocate career overview
Index: 150, Preprocessed Text : organized dependable candidate successful managing
Index: 151, Preprocessed Text : skill prospecting cold calling team
Index: 152, Preprocessed Text : ambitious dedicated managed care professional
Index: 153, Preprocessed Text : sexual assault crisis counselor victim
Index: 154, Preprocessed Text : client negotiation mediation skill client
Index: 155, Preprocessed Text : technical qualification window m officeeducation
Index: 156, Preprocessed Text : company drafting communication required management
Index: 157, Preprocessed Text : doctorate prepared registered nurse medical
Index: 158, Preprocessed Text : highly motivated creative professional strong
Index: 159, Preprocessed Text : nurse practitioner focused providing quality
Index: 160, Preprocessed Text : continue professional human resource career
Index: 161, Preprocessed Text : vice president executive profile accomplished
Index: 162, Preprocessed Text : landscaper accomplishment fmc level certification
Index: 163, Preprocessed Text : experienced working fast paced environment
Index: 164, Preprocessed Text : agile hungry project manager nearly
Index: 165, Preprocessed Text : professional knowledgeable receptionist versed administrative
Index: 166, Preprocessed Text : master prepared administrative assistant seeking
Index: 167, Preprocessed Text : corporate trainer performance coach twenty
Index: 168, Preprocessed Text : client relation advocate career overview
Index: 169, Preprocessed Text : level critical platform support engineer
Index: 170, Preprocessed Text : objective obtain rn position intake
Index: 171, Preprocessed Text : find new challenging position utilize
Index: 172, Preprocessed Text : reliable highly accurate phlebotomist preceptor
Index: 173, Preprocessed Text : highly motivated skilled individual extensive
Index: 174, Preprocessed Text : necessary document referral attorney necessary
Index: 175, Preprocessed Text : experienced marketing sale consultant looking
Index: 176, Preprocessed Text : passionate dedicated professional five year
Index: 177, Preprocessed Text : seeking setting expand use sale
Index: 178, Preprocessed Text : driven compassionate health wellness professional
Index: 179, Preprocessed Text : president chief executive officer executive
Index: 180, Preprocessed Text : education detail com university clacutta
Index: 181, Preprocessed Text : seeking position using strong organizational
Index: 182, Preprocessed Text : self motivated result oriented resourceful
Index: 190, Preprocessed Text : direct client coordinator counselor victim
Index: 193, Preprocessed Text : certified massachusetts domestic violence sexual
Index: 194, Preprocessed Text : lead pharmacy technician advocate supervisor
Index: 196, Preprocessed Text : highly motivated licensed social worker
Index: 197, Preprocessed Text : obtain position provide necessary tool
Index: 198, Preprocessed Text : outlined result recommendation improvement develop
Index: 199, Preprocessed Text : md coordinator skill skill used
Index: 200, Preprocessed Text : responsible mature retail sale consultant
Index: 201, Preprocessed Text : highly motivated result detail oriented
Index: 202, Preprocessed Text : two solid year experience medical
Index: 203, Preprocessed Text : registered nurse clinical care coordinator
Index: 204, Preprocessed Text : rn asst head nurse practice
Index: 205, Preprocessed Text : result oriented manager thrives fast
Index: 206, Preprocessed Text : detail oriented human resource professional
Index: 207, Preprocessed Text : afforded opportunity apply advanced administrative
Index: 208, Preprocessed Text : transaction performing cash accounting journal
Index: 209, Preprocessed Text : report monday get customer helping
Index: 210, Preprocessed Text : obtain position corporation benefit highly
Index: 211, Preprocessed Text : highly motivating detail oriented adaptable
Index: 212, Preprocessed Text : customer success advocate professional profile
Index: 213, Preprocessed Text : outstanding customer service skill proven
Index: 214, Preprocessed Text : conscientious attorney experience government relation
Index: 215, Preprocessed Text : organized hardworking reliable social worker
Index: 216, Preprocessed Text : member advocate education university incarnate
Index: 217, Preprocessed Text : patient advocate professional profile detail
Index: 218, Preprocessed Text : patient advocate career overview skilled
Index: 219, Preprocessed Text : motivated professional practical analytical operational
Index: 220, Preprocessed Text : plan description ensure proper timely
Index: 221, Preprocessed Text : compassionat social service professional active
Index: 222, Preprocessed Text : dynamic shelter advocate year clerical
Index: 223, Preprocessed Text : administrative support professional experience working
Index: 224, Preprocessed Text : talented bachelor art graduate seeking
Index: 225, Preprocessed Text : customer advocate career overview enthusiastic
Index: 226, Preprocessed Text : depth knowledge taking order compute
Index: 227, Preprocessed Text : high energy manager successful building
Index: 228, Preprocessed Text : obtain position would utilize strong
Index: 229, Preprocessed Text : school success advocate accomplishment ymca
Index: 230, Preprocessed Text : compassionate professional crisis specialist belief
Index: 231, Preprocessed Text : obtain position company education bba
Index: 232, Preprocessed Text : guadalajara jalisco mexico eight year
Index: 233, Preprocessed Text : motivated business analyst technical expertise
Index: 234, Preprocessed Text : industrious organized professional excellent analytical
Index: 235, Preprocessed Text : dedicated public health administrator adept
Index: 236, Preprocessed Text : seeking opportunity management hr department
Index: 237, Preprocessed Text : motivated enthusiastic responsible goal oriented
Index: 238, Preprocessed Text : recently completed five year military
Index: 239, Preprocessed Text : represent reputable company underwriter proving
Index: 240, Preprocessed Text : benefit advocate career overview customer
Index: 241, Preprocessed Text : empowered health advocate excellent communication
Index: 242, Preprocessed Text : qualified lead customer service representative
Index: 243, Preprocessed Text : detail oriented administrative clerical support
Index: 244, Preprocessed Text : customer service professional dedicated effective
Index: 245, Preprocessed Text : social worker five year experience
Index: 246, Preprocessed Text : seeking part time prn generalist
Index: 247, Preprocessed Text : eleven year experience management criminal
Index: 248, Preprocessed Text : organized professional passion help others
Index: 249, Preprocessed Text : talented customer service manager skilled
Index: 250, Preprocessed Text : child family advocate professional profile
Index: 251, Preprocessed Text : dedicated focused community advocate excels
Index: 252, Preprocessed Text : apply creative problem solving management
Index: 253, Preprocessed Text : customer care professional pursuing position
Index: 254, Preprocessed Text : job title adept identifying documenting
Index: 255, Preprocessed Text : financial professional self starter capable
Index: 256, Preprocessed Text : key member stakeholder relation branch
Index: 257, Preprocessed Text : dedicated professional excellent technical analytical
Index: 258, Preprocessed Text : costumer representative background sandwich artist
Index: 259, Preprocessed Text : environmental biologist experienced researcher expertise
Index: 260, Preprocessed Text : service oriented process operator five
Index: 261, Preprocessed Text : joined ministry education posted bailey
Index: 262, Preprocessed Text : build career local community improve
Index: 263, Preprocessed Text : compassionate security aide strong experience
Index: 264, Preprocessed Text : enthusiastic computer engineer eager contribute
Index: 265, Preprocessed Text : result driven diligent highly accomplished
Index: 266, Preprocessed Text : biological science technician four year
Index: 267, Preprocessed Text : safety intern area expertise occupational
Index: 268, Preprocessed Text : highly skilled growth mindset professional
Index: 269, Preprocessed Text : graduate research assistant profile result
Index: 270, Preprocessed Text : extensive financial experience together several
Index: 271, Preprocessed Text : rn staff nurse professional experience
Index: 272, Preprocessed Text : enthusiastic chemist eager pursue lasting
Index: 273, Preprocessed Text : post doctoral research fellow professional

In [95]:
print(df_cv1.columns)

Index(['Resume_test', 'category', 'clean_data'], dtype='object')

In [96]:
df_cv1 = df_cv1.drop(columns=['Resume_test'])
df['text_length'] = df['clean_data'].apply(lambda x: len(x.split()))
print(df['text_length'].describe())

count     166.000000
mean      265.283133
std       235.009242
min        12.000000
25%        90.000000
50%       194.500000
75%       363.250000
max      1292.000000
Name: text_length, dtype: float64

In [97]:
df_cv1.head()

     category                                         clean_data
0  accountant  result oriented organized bilingual accounting...
1  accountant  flexible accountant adapts seamlessly constant...
2  accountant  highly analytical detail oriented professional...
3  accountant  analysis prepare auction sale journal finalize...
4  accountant  eleven year experience accounting profession b...

In [99]:
df_cv1.to_csv("C:\code\project-ky8\Data-mining\data_mining\dataresume30k.csv")