In [ ]:
!pip install ftfy

Requirement already satisfied: ftfy in /usr/local/lib/python3.12/dist-packages (6.3.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from ftfy) (0.2.14)

In [ ]:
import sqlite3
import re
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib
matplotlib.rcParams["figure.figsize"] = (10,6)
import ast
import json
import ftfy # Thư viện sửa lỗi mã hóa
import unicodedata
from sklearn.linear_model import LinearRegression
import seaborn as sns
from difflib import get_close_matches

In [ ]:
# Kết nối tới file
conn = sqlite3.connect('jobs.db')

In [ ]:
# Đọc danh sách các bảng
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
print("Các bảng có tronga file:", tables)

Các bảng có tronga file:    name
0  jobs

In [ ]:
  # Đọc thử một bảng vào DataFrame (ví dụ bảng 'job_postings')
df = pd.read_sql("SELECT * FROM jobs", conn)
df.head()

,id,title,company_name,location,source,source_url,description,requirements_text,job_type,level,...,certifications,required_skills,preferred_skills,benefits,company_rating,is_remote,is_active,created_at,updated_at,crawled_at
0,3462,Frontend developer (PA project),CUBICASA,"Quận 1, Hồ Chí Minh",topdev,https://topdev.vn/detail-jobs/frontend-develop...,Your role & responsibilities:\nWe’re looking f...,Your skills & qualifications:\n\nExperience in...,Full-time,Manager,...,None,"[""CSS"", ""HTML"", ""Git"", ""Restful Api"", ""SASS"", ...",None,"[""13th month bonusParticipate in large-scale a...",None,0,1.0,2026-01-11 15:11:56,2026-01-18 10:57:55,2026-01-11 15:11:56
1,3463,QA Engineer (Automotive),42dot Vietnam,"Thành phố Hồ Chí Minh, Hồ Chí Minh",topdev,https://topdev.vn/detail-jobs/qa-engineer-auto...,None,None,Full-time,None,...,None,"[""QA"", ""Tester"", ""Unit Testing"", ""Integration ...",None,"[""Premium office in District 1, free parking, ...",None,0,1.0,2026-01-11 15:12:00,2026-01-18 13:56:10,2026-01-11 15:12:00
2,3464,Java Developer,WEEDS VINA,"Quận Đống Đa, Hà Nội",topdev,https://topdev.vn/detail-jobs/java-developer-w...,None,None,Full-time,None,...,None,"[""Java"", ""JavaScript"", ""JQuery"", ""VueJS"", ""Rea...",None,"[""Attractive salary, 13th month salary, other ...",None,0,1.0,2026-01-11 15:12:04,2026-01-18 13:56:10,2026-01-11 15:12:04
3,3465,Nhân viên chế bản - Webtoon/ Manga - Full-time,DaouKiwoom Innovation,"Quận Bình Thạnh, Hồ Chí Minh",topdev,https://topdev.vn/detail-jobs/nhan-vien-che-ba...,None,None,Full-time,None,...,None,"[""Photoshop""]",None,"[""Competitive salary, salary review once a yea...",None,0,1.0,2026-01-11 15:12:08,2026-01-18 10:01:51,2026-01-11 15:12:08
4,3466,Webtoon Colorist - Họa sĩ tô màu - Full-time,DaouKiwoom Innovation,"Quận Bình Thạnh, Hồ Chí Minh",topdev,https://topdev.vn/detail-jobs/webtoon-colorist...,None,None,Full-time,None,...,None,None,None,"[""Competitive salary, salary review once a yea...",None,0,1.0,2026-01-11 15:12:11,2026-01-18 10:01:52,2026-01-11 15:12:11

In [ ]:
df.shape
df.columns

Index(['id', 'title', 'company_name', 'location', 'source', 'source_url',
       'description', 'requirements_text', 'job_type', 'level', 'salary_min',
       'salary_max', 'salary_currency', 'salary_text', 'experience_years_min',
       'experience_years_max', 'education_level', 'certifications',
       'required_skills', 'preferred_skills', 'benefits', 'company_rating',
       'is_remote', 'is_active', 'created_at', 'updated_at', 'crawled_at'],
      dtype='object')

In [ ]:
df.info() #Thông tin tổng quan
df.describe()
df.isnull().sum() # đếm giá trị thiếu

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12117 entries, 0 to 12116
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    12117 non-null  int64
 1   title                 12117 non-null  object
 2   company_name          12117 non-null  object
 3   location              12049 non-null  object
 4   source                12117 non-null  object
 5   source_url            12117 non-null  object
 6   description           11989 non-null  object
 7   requirements_text     10044 non-null  object
 8   job_type              12117 non-null  object
 9   level                 11862 non-null  object
 10  salary_min            4723 non-null   float64
 11  salary_max            4739 non-null   float64
 12  salary_currency       9296 non-null   object
 13  salary_text           5481 non-null   object
 14  experience_years_min  4479 non-null   float64
 15  experience_years_max  2564 non-null   float64
 16  education_level       1154 non-null   object
 17  certifications        7303 non-null   object
 18  required_skills       9505 non-null   object
 19  preferred_skills      7303 non-null   object
 20  benefits              9496 non-null   object
 21  company_rating        0 non-null      object
 22  is_remote             12117 non-null  int64
 23  is_active             10186 non-null  float64
 24  created_at            5567 non-null   object
 25  updated_at            12117 non-null  object
 26  crawled_at            12117 non-null  object
dtypes: float64(5), int64(2), object(20)
memory usage: 2.5+ MB

id                          0
title                       0
company_name                0
location                   68
source                      0
source_url                  0
description               128
requirements_text        2073
job_type                    0
level                     255
salary_min               7394
salary_max               7378
salary_currency          2821
salary_text              6636
experience_years_min     7638
experience_years_max     9553
education_level         10963
certifications           4814
required_skills          2612
preferred_skills         4814
benefits                 2621
company_rating          12117
is_remote                   0
is_active                1931
created_at               6550
updated_at                  0
crawled_at                  0
dtype: int64

**xử lý trùng**

In [ ]:
print("Trước:", len(df))
df = df.drop_duplicates(subset=["title", "company_name","source_url"])
print("Sau:", len(df))

Trước: 12117
Sau: 12086

In [ ]:
print("Trước:", len(df))
df = df.drop_duplicates(subset=["title", "company_name","source"])
print("Sau:", len(df))

Trước: 12086
Sau: 10556

**Loại bỏ nếu description và requirements_text null**

In [ ]:
print("Trước:", len(df))
df = df.dropna(subset=["description", "requirements_text"], how="all")
print("Sau:", len(df))

Trước: 10556
Sau: 10439

**Đánh label cho level**

In [ ]:
df['level'].unique()

array(['Manager', 'Senior', 'Lead', 'Intern', 'Junior', 'Mid', None,
       'Entry', 'Director', 'Seniority levelMid-Senior level',
       'Seniority levelEntry level', 'Seniority levelAssociate',
       'Seniority levelExecutive', 'Seniority levelDirector'],
      dtype=object)

In [ ]:
import re
from typing import Optional

# Danh sách pattern theo mức độ ưu tiên (từ cao → thấp)
LEVEL_PATTERNS = [
    ("Intern",   r"\b(intern|internship|thực\s*tập)\b"),
    ("Fresher",  r"\b(fresher|graduate|new\s*grad)\b"),
    ("Junior",   r"\b(junior|jr)\b"),
    ("Middle",      r"\b(mid|middle|mid[-\s]?level)\b"),
    ("Senior",   r"\b(senior|sr)\b"),
    ("Lead",     r"\b(tech\s*lead|lead|leader)\b"),
    ("Manager",  r"\b(manager|head|director)\b"),
]

def extract_level(title: Optional[str]) -> Optional[str]:
    """
    Trích xuất level công việc từ tiêu đề (job title).
    Nếu không xác định được level → giữ nguyên giá trị null (None).
    """

    if title is None or not isinstance(title, str):
        return None

    title = title.lower().strip()

    for level, pattern in LEVEL_PATTERNS:
        if re.search(pattern, title, flags=re.IGNORECASE):
            return level

    return None

In [ ]:
import pandas as pd

df["level"] = df["title"].apply(extract_level)

print(df)

          id                                              title  \
0       3462                    Frontend developer (PA project)
8       3470             TIGER TRIBE – SENIOR BACKEND DEVELOPER
16      3478  Lead Full-stack Developer (.NET, Angular/React...
20      3482                APAC DATA HUB – SENIOR DATA SCIENCE
21      3483                          HRIS Technical Specialist
...      ...                                                ...
12110  15572                   Artificial Intelligence Engineer
12112  15574                                Senior Data Analyst
12114  15576                                       Data Analyst
12115  15577                                       Data Analyst
12116  15578              AUM Flow Analytics – MSIM – Associate

                                           company_name  \
0                                              CUBICASA
8                                           TIGER TRIBE
16                                              EMESOFT
20                                          TIGER TRIBE
21     Ngân hàng TMCP Công Thương Việt Nam (Vietinbank)
...                                                 ...
12110                                          Teradata
12112                                           Verkada
12114                                   Swish Analytics
12115                                            Anchin
12116                                    Morgan Stanley

                          location    source  \
0              Quận 1, Hồ Chí Minh    topdev
8              Quận 1, Hồ Chí Minh    topdev
16      Quận Tân Bình, Hồ Chí Minh    topdev
20             Quận 1, Hồ Chí Minh    topdev
21          Quận Hoàn Kiếm, Hà Nội    topdev
...                            ...       ...
12110  Hyderabad, Telangana, India  linkedin
12112                San Mateo, CA  linkedin
12114            San Francisco, CA  linkedin
12115                 New York, NY  linkedin
12116                 New York, NY  linkedin

                                              source_url  \
0      https://topdev.vn/detail-jobs/frontend-develop...
8      https://topdev.vn/detail-jobs/tiger-tribe-seni...
16     https://topdev.vn/detail-jobs/lead-full-stack-...
20     https://topdev.vn/detail-jobs/apac-data-hub-se...
21     https://topdev.vn/detail-jobs/hris-technical-s...
...                                                  ...
12110  https://in.linkedin.com/jobs/view/artificial-i...
12112  https://www.linkedin.com/jobs/view/senior-data...
12114  https://www.linkedin.com/jobs/view/data-analys...
12115  https://www.linkedin.com/jobs/view/data-analys...
12116  https://www.linkedin.com/jobs/view/aum-flow-an...

                                             description  \
0      Your role & responsibilities:\nWe’re looking f...
8      Your role & responsibilities:\nDesign, develop...
16     Your role & responsibilities:\nLeading the dev...
20     Your role & responsibilities:\nResponsible for...
21     Your roles & responsibilities:\n1. Work object...
...                                                  ...
12110  Our Company:\nAt Teradata, we believe that peo...
12112  Who We Are\nVerkada is transforming how organi...
12114  Company Overview\nSwish Analytics is a sports ...
12115  Title\n: Data Analyst\nDepartment\n: IT\nSuper...
12116  Morgan Stanley is a leading global financial s...

                                       requirements_text    job_type   level  \
0      Your skills & qualifications:\n\nExperience in...   Full-time    None
8      Your skills & qualifications:\n\n5+ years of e...   Full-time  Senior
16     Your skills & qualifications:\n\nA Bachelor’s ...   Full-time    Lead
20     Your skills & qualifications:\n\nBA/MSc in Sta...   Full-time  Senior
21     Your skills & qualifications:\n\nTraining leve...   Full-time    None
...                                                  ...         ...     ...
12110  Our Company:\nAt Teradata, we believe that peo...  Internship    None
12112  Who We Are\nVerkada is transforming how organi...   Full-time  Senior
12114  Own and manage the full lifecycle of dashboard...   Full-time    None
12115  Design, build, debug, and maintain queries, vi...    Contract    None
12116  Assist in the production of daily, weekly, and...   Full-time    None

       ...          certifications  \
0      ...                    None
8      ...                    None
16     ...                    None
20     ...                    None
21     ...                    None
...    ...                     ...
12110  ...                      []
12112  ...                      []
12114  ...                      []
12115  ...  "[\"Pub\", \"based\"]"
12116  ...                      []

                                         required_skills preferred_skills  \
0      ["CSS", "HTML", "Git", "Restful Api", "SASS", ...             None
8      ["ASP.NET", "C#", ".NET", "SQL Server", "Restf...             None
16     ["C#", ".NET", "ReactJS", "Angular", ".NET Core"]             None
20     ["Python", "Data Science", "Azure", "CI/CD", "...             None
21                            ["Oracle", "PL/SQL", "AI"]             None
...                                                  ...              ...
12110  "[\"AI\", \"AWS\", \"Agile\", \"Azure\", \"Doc...             null
12112  "[\"AI\", \"Data Science\", \"Python\", \"data...             null
12114  "[\"AWS\", \"Data Science\", \"Git\", \"MySQL\...             null
12115               "[\"SQL Server\", \"data science\"]"             null
12116                                                 []               []

                                                benefits  company_rating  \
0      ["13th month bonusParticipate in large-scale a...            None
8      ["Fixed Bonus: 13th Variable Bonus: 1~3 months...            None
16     ["Salary in probation time: 100%", "Bonus: 13t...            None
20     ["Fixed Bonus: 13th Variable Bonus: 1~3 months...            None
21     ["VietinBank's salary mechanism is built scien...            None
...                                                  ...             ...
12110                                     "[\"equity\"]"            None
12112  "[\"Collaborate with stakeholders to design me...            None
12114                                                 []            None
12115                                                 []            None
12116                          "[\"vision\", \"bonus\"]"            None

       is_remote is_active           created_at           updated_at  \
0              0       1.0  2026-01-11 15:11:56  2026-01-18 10:57:55
8              0       1.0  2026-01-11 15:12:27  2026-01-18 13:56:11
16             0       1.0  2026-01-11 15:12:58  2026-01-18 13:56:12
20             0       1.0  2026-01-11 15:13:13  2026-01-18 13:56:12
21             0       1.0  2026-01-11 15:13:17  2026-01-18 13:56:12
...          ...       ...                  ...                  ...
12110          0       1.0                 None  2026-01-21 12:02:35
12112          0       1.0                 None  2026-01-21 12:02:35
12114          1       1.0                 None  2026-01-21 12:02:36
12115          0       1.0                 None  2026-01-21 12:02:36
12116          0       1.0                 None  2026-01-21 12:02:36

                crawled_at
0      2026-01-11 15:11:56
8      2026-01-11 15:12:27
16     2026-01-11 15:12:58
20     2026-01-11 15:13:13
21     2026-01-11 15:13:17
...                    ...
12110  2026-01-21 10:55:39
12112  2026-01-21 10:56:31
12114  2026-01-21 10:56:44
12115  2026-01-21 10:57:05
12116  2026-01-21 10:57:47

[10439 rows x 27 columns]

In [ ]:
for title in df['title'].unique():
    print(title)

Frontend developer (PA project)
TIGER TRIBE – SENIOR BACKEND DEVELOPER
Lead Full-stack Developer (.NET, Angular/React.js)
APAC DATA HUB – SENIOR DATA SCIENCE
HRIS Technical Specialist
Senior QA Engineer (Creative & Development Tools)
Phân tích Nghiệp Vụ (Business Analyst)
PHP 5Y+ – Sub Lead / Team Lead (Payment System)
Senior Data Engineer (40000063)
DEVOPS ENGINEER (Upto $2000 Gross)
SENIOR JAVA DEVELOPER (Onboard sau tết)
TIGER TRIBE – MOBILE DEVELOPER INTERN
Junior QA
AI/NLP Engineer / Algorithm Engineer– Junior/Mid/Senior- English
AI ENGINEER (JUNIOR/MIDDLE)
VOIP System Engineer
Automation Tester (Playwright, Selenium, QA/QC)
JUNIOR DEVELOPER (MOBILE APP)
Game 3D Artist
Firmware Developer
Senior Java
PHP DEVELOPER - HO CHI MINH
Java Software Engineer
JAVA Developer
Middle PHP Developer
Lập trình viên Angular (Làm Việc Thứ 2 –  Thứ 6)
Technical Lead (Web & App Projects)
BUSINESS ANALYST - Platform
Mobile Game Developer (Senior)
Business Analyst
NHÂN VIÊN KIỂM THỬ PHẦN MỀM (QC/Tester)
PHP Software Engineer
Senior Frondtend Developer
Chuyên viên BA (phân tích nghiệp vụ) (Product BA, Domain HRM)
Manual Test (Làm Việc Thứ 2 – Thứ 6)
BUSINESS ANALYST (BA)
Senior Backend JAVA
Lập trình viên FrontEnd
Fullstack Dev
AI ENGINEER (Middle/Senior)
Fullstack Developer (ReactJS + Python) – Junior / Mid - English
(HCM) Chuyên viên Kiến trúc hạ tầng (Devops Engineer)
Quality Control
UI/UX Designer
Business Analyst (BA) kiêm Quality Assurance (QA)
THỰC TẬP SINH QA – BA (Quality Assurance / Business Analyst Intern)
Senior Android Developer (Signing Bonus)
Senior UI Designer (10 headcounts)
Chuyên viên Back-end Developer
Fresher/Junior PHP Developer
ANDROID DEVELOPER
BUSINESS ANALYST
AI Data Engineer – AI Assistant Platform
Tech Lead AI
DevOps Engineer - Mức lương Upto 45M
Backend Developer (Middle)
Project Manager
Director thị trường Việt Nam (Crypto/FX)
Product Owner (Làm SP AI)
Backend Engineer
ODOO DEVELOPER - HO CHI MINH
THỰC TẬP SINH TESTER / QC (CÓ LƯƠNG/PHỤ CẤP)
[Junior to Senior] Full Stack Developer
Lập trình viên Mobile Developer
Back-end Developer
Senior, Technical Lead Engineer (Python, PHP)
Developer (Hà Nội)
QA Leader - Mức lương upto 40M
Parttime IT Server Manager
Senior DevOps  & Cloud Database Reliability Engineer (Azure / PostgreSQL / MongoDB)
PO - AI Assistant Platform
Chuyên viên Quản trị hệ thống - SYSTEM Engineer - Upto 35M
IT SUPPORT
BRIDGE SYSTEM ENGINEER (BRSE)
Chuyên viên tư vấn khách hàng (dịch vụ 1-1)
QA Engineer – Logistics System
Lập trình viên Mobile App
Middle Backend Developer
KỸ THUẬT VIÊN BẢO TRÌ HẠ TẦNG VIỄN THÔNG (GIA LÂM, LONG BIÊN)
Nhân Viên Phục Vụ Nhà Hàng Fulltime/Parttime - Biên Hòa (Đi Làm Ngay)
Chuyên viên cao cấp Quan hệ khách hàng Doanh nghiệp - Bậc 1 (RM) - Tỉnh Đồng Nai
Chuyên viên cao cấp Quan hệ khách hàng Doanh nghiệp - Bậc 1 (RM) - Tỉnh Đăk Nông | Tỉnh Gia Lai | Tỉnh Đăk Lăk
Chuyên viên cao cấp Quan hệ khách hàng Doanh nghiệp - Bậc 2 (SRM) - Tỉnh Đăk Nông | Tỉnh Gia Lai | Tỉnh Đăk Lăk
Chuyên viên kinh doanh bảo hiểm - Tỉnh Nam Định | Tỉnh Hà Nam | Tỉnh Bắc Giang | Tỉnh Nghệ An | Tỉnh Quảng Trị | Tỉnh Hưng Yên | Tỉnh Thái Bình | Tỉnh Thanh Hóa | Tỉnh Hà Tĩnh | Thành phố Hải Phòng | Tỉnh Quảng Bình | Tỉnh Ninh Bình | Tỉnh Bắc Ninh | Tỉnh
[Vinhomes] Giám đốc Ban quản lý Xây dựng
DATA & MEDIA STRATEGY LEAD
Chuyên viên cao cấp kinh doanh bảo hiểm - Tỉnh Đăk Nông | Tỉnh Lâm Đồng | Tỉnh Gia Lai | Tỉnh Đăk Lăk | Tỉnh Kon Tum
Kỹ Sư Chất Lượng (PQA, VQM, QE, ISO)
Chuyên viên HT Marketing/Digital
Trưởng nhóm Khai thác tài sản Miền Nam
CVC/CVCC Nâng Cao Trải Nghiệm Khách Hàng - Hà Nội - TA112
Junior Graphic Designer (FASHION)
CV/CVC/CVCC Bán Hàng Trực Tiếp - Trung tâm Bán hàng Chuyên biệt thẻ tín dụng - TA160
NV/CV Tư vấn tài chính cá nhân - Bình Chánh, Tây Ninh, Đồng Tháp - TA158
ACBA - Chuyên viên Quản Lý & Khai Thác Tài Sản
CN Bình Dương - Giám đốc Quản lý Khách hàng Cá nhân Priority
Content Executive (B2B Tech & Talent Community)
Lead Generation Manager (B2B Digital Innovation)
Credit Risk Management Policy Specialist/ Expert For Unsecured Lending- Hà Nội/ Hồ Chí Minh- TA084
Accountant Executive (Singapore)
[Đồng Nai] Phó Giám đốc Chi nhánh phụ trách KHCN
CVCC Bán sản phẩm cho vay Thế chấp - TPHCM (Quận 5, Quận 6, Tân Bình, Tân Phú, Hóc Môn, Bình Chánh, Củ Chi) - TA115
Graphic Designer
CVC/CVCC Khách Hàng Doanh Nghiệp Vừa Và Nhỏ - Đống Đa, Hai Bà Trưng - Hà Nội - TA148
Kỹ Sư Xây Dựng - Biết Tiếng Anh
Performance Marketing (App focus)
Chuyên gia Sản xuất (Sản phẩm Bao bì)
2D Graphic Designer (Anime/Manga Artist)
CVCC Tư vấn tài chính cá nhân - TPHCM - TA115
PS admin and quotation Writer
EXPORT SALES MANAGER
Kỹ sư Trắc Đạc (Gia Lai)
Engineering Consultant
Bác sĩ Thú y (Gia Lai)
Kỹ sư Thiết kế Giao thông - Hạ tầng Kỹ thuật (Gia Lai)
Nhân Viên/Chuyên Viên Thu Hồi Nợ Hiện trường - Đông Nam Bộ & MeKong - TA080
BUSINESS DEVELOPMENT MANAGER
Social Media Executive
Chuyên viên Khai thác tài sản Miền Bắc
Trợ lý Kỹ thuật (Chuối, Dứa, Sầu riêng, Xoài, Bưởi) - Gia Lai
Trợ lý Kế hoạch (Trồng trọt, Chăn nuôi) - Gia Lai
Kỹ sư Cơ khí (Gia Lai)
Nhân Viên Video Editor
Chủ nhiệm sản phẩm (PO) - Unsecured Lending
CV Ban Thư ký HĐQT & QHCĐ (Mảng Pháp chế)
IT Comtor Mảng Lập Trình Nhúng (từ N2) (Bình Thạnh)
Kỹ sư Kinh tế Xây dựng (Gia Lai)
Chuyên viên Kỹ thuật Sản xuất Công nghiệp (Gia Lai)
Chuyên viên Hỗ trợ kinh doanh Agent Banking
(JP) Vận Hành Máy CNC (Nữ Làm Được, Có Chỗ Ở)
Senior Brand Manager (Mainstream)
[HEINEKEN Thường Tín, Hà Nội] Kỹ thuật viên Bảo trì Cơ khí - Mechanical Technician
Đại Diện Tiêu Thụ (Sales Representative)- Xuân Lộc, Đồng Nai (Kênh Horeca)
Pessoa Analista Recursos Humanos SR (Business Partner) - Alagoinhas
Personal Assistant to HGSS Director
Kỹ sư Thiết kế Hệ thống Điều hòa Không khí (Gia Lai)
[GO] Chuyên Viên/Chuyên Viên Cao Cấp Khách Hàng Cá Nhân - KV Miền Bắc
CV/ CVCC Quan Hệ Khách Hàng Cá Nhân - MIỀN TRUNG & TÂY NGUYÊN (Golden Opportunity)
CV/ CVCC Quan Hệ Khách Hàng Doanh Nghiệp - MIỀN TRUNG & TÂY NGUYÊN (Golden Opportunity)
Business Development (Sales B2B, AI Agent)
Trưởng phòng dịch vụ khách hàng - Khu vực Miền Bắc
HO - Giám Đốc Phát Triển Thu Hút Khách Hàng (Acquisition/ Engagement Campaign)
[ Long Thành - Đồng Nai ] Nhân Viên Tư Vấn Bán Hàng Tại Fpt Shop
Chuyên Viên Quan Hệ Khách Hàng Cá Nhân - Khu Vực Đồng Nai
Giao Dịch Viên - Hà Nội (Khu Vực Hoàng Mai, Thanh Xuân, Hai Bà Trưng)
Chuyên Viên Hỗ Trợ Kinh Doanh Nguồn Vốn - Hội Sở Hà Đông (Hà Nội)
CVCC/CG Quản Trị Rủi Ro Công Nghệ Thông Tin (Digital Channel Risk Management Specialist)
Chuyên Viên Thiết kế Biện pháp Thi công
[ Xã An Phước - Đồng Nai ] Nhân Viên Tư Vấn Bán Hàng Tại Fpt Shop
Chuyên viên Digital Marketing
Head of Sales (Medical Devices)
[Long Biên] Giao dịch viên
Chuyên Gia Quản Lý Sản Phẩm (Am hiểu ngành FMCG) - TP Hồ Chí Minh - TA175 - ID399
TMO - Product Owner (Số hóa hành trình Tích lũy & Đầu tư)
GĐCC Kinh doanh Commodity, Vàng và Carbon Credit - TA133 - ID404
Giám Đốc Dự Án Công Nghệ (Blockchain)
Hoài Nhơn - CV/CVC/CVCC Quan hệ KHCN Priority
HO - Giám Đốc Bán Hàng Ngân Hàng Giao Dịch (Manager of Transaction Banking)
Managing Director
Giám Đốc Phòng Khách Hàng Doanh Nghiệp - Khu Vực Biên Hòa, Đồng Nai
Nhân viên bán hàng siêu thị AVAKids
Software Analyst
UI/UX Designer Mid/Senior, English Required
Junior Game Designer
Database Administrator PostgreSQL, AWS, Agile
Senior Back-end Python Developer FastAPI, AWS
Senior PHP Software Engineer New Project
QA Automation Engineer Python, TypeScript, QA QC
Senior Android Engineer
Senior Frontend Developer
Caspeco-Senior Backend .NET Dev .NET Core, C#, Azure
Flutter/iOS Developer Objective-C/Swift
Salesforce Developer All level  Up to 55M VND
Senior-Lead Product Owner / Product Manager
Phan tich nghiep vu BA
Fullstack Engineer Typescript/PHP, English
Senior Data Engineer
Junior Fullstack Engineer Python/Django, English
Power BI Developer
Fullstack Engineer Python/Django, English
Senior AI Engineer
Mobile Developer
Fullstack Dev - AI products
Full Stack Developer Python, AWS
Ruby on Rails Developer Middle/Senior
Cloud  Database Ops
DevOps Engineer Database Experience
Automotive Software Engineer C++, OOP, Middleware
Senior Manager, Data Solution Delivery
Senior Backend Developer Golang
05 Senior PHP Developers Laravel / Symfony
IAM Security Engineering CIAM  Auth0, English
IAM Security Engineering SailPoint, English
Software Engineering Manager
Cyber Security Consultant
Security Engineer
IT RISK and COMPLIANCE
10 Automation Test Engineer all level
Senior Game Designer
Senior Backend Golang Engineer
Mid/Senior Fullstack Developer NodeJS, English x2
QA Executive QA QC, Tester - 1 year contract
QA Engineer Manual  Automation - 2 Openings
Mid/Senior Android Engineer Kotlin/Java, English
ERP Specialist D365 - Finance Focus
Senior Fullstack Java Engineer
Senior Product Owner
CV Phat trien ung dung Java Developer
 Full-Stack Developer ReactJS/ NodeJS
Sign-on Bonus Project Leader/ BrSE Japanese N2+
IT Auditor/ IT Risk Manager Security, ISO 27001, ITIL
Technical Project Manager Automotive Chiplet/10 years
Senior Embedded Driver Engineer POSIX OS, LinuxKernel
Software Engineer Java, Golang, NodeJS
DevOps Engineer CI/CD, Kubernetes
Senior/Lead QA Engineer QE, QC, Automation Tester
10 Senior Embedded Security Engineer  Linux/ Android
Test Automation Engineer System Focus
Junior/Fresher Back-end Dev  NodeJS/Python/ OOP
Middle Backend Engineer NodeJS/ PHP/ Python/ MySQL
QA/QC Engineer Manual, Automation
Backend Developer Java/Mid-Senior Level
Junior Game QA Quality Assurance
Data Quality Management Specialist
Chuyen vien Phan tich va thiet ke Mo hinh Du lieu
Data Architect Oracle, PostgreSQL, MongoDB, Redis, S3
Data Analyst Retail Banking
Data Engineer Oracle, BI Tableau, BI publisher, Cloud
CV, CVCC Khoa hoc Du lieu - Data Scientist
Chuyen vien Chinh sach DL-Data Governance Specialist
DevOps Engineer
DevSecOps Engineer
IT Service Quality Specialist ITIL, Incident, ISO
Android Engineer Kotlin
Graph Data Engineer - Financial Crime
Chuyen vien cao cap Phat trien giai phap Du lieu
Chuyen gia Quan tri Du lieu
 UI/UX Designer
Senior AUTOSAR Engineer onsite JP long-term
Mobile App Development Engineer Unity or React Native
React Native Mobile App Development Engineer Expo
Truong phong Giai phap Du lieu va Phan tich
Engineering Director Open for Expat
Java/Kotlin Engineer Senior/PrincipalBanking Project
Fullstack Developer 2 yrs exp, PHP, Laravel, NextJS
Senior Automation Tester
Bridge Engineer cum Project Manager Japanese N2  3k
Bridge Software Engineer BrSE, PO, Japanese
Senior/Manager QA QC Engineer Tester, Japanese N2+
Senior Bridge Engineer - BrSE Japanese N2+
Senior/Principal Ruby on Rails Developer AWS, Backend
IT Operations Manager Global Operation
Golang Developer From 3-Year Experience To Lead
Frontend Developer Mobile
Viettel Asset/Ky su phat trien phan mem Developer
DevOps Engineer AWS/ Kubernetes/ Linux/ CI/CD
Viettel Asset/Project Manager Nen tang Developer
Process Quality Assurance PQA
Business Analyst Quality Assurance, English
Senior Backend Engineer AI-Driven
Frontend Engineer JavaScript/ReactJS - Captcha
 Backend Developer  Java, NodeJS, PHP, Python - VIC
MLOps Engineer
Senior Frontend Developer NextJS, TypeScript, AWS
Infra Manager DevOps Manager
Mobile Flutter/ React Native Developer - VIC
Infrastructure  System Administrator Linux
Manual/Automation QC Engineer QA QC/Tester
Middle/Senior Mobile Developer Flutter, Dart, CI/CD
Frontend Lead
Fresher  Junior - Software Developer .NET, Java, C#
Android App Developer Java/ Kotlin
Tech Lead Manager Hands-on .NET/ React
Ruby on Rails Engineer Tech Lead/Senior
Android Engineer Java/Kotlin - Hanoi
QA/QC Engineer Unit Test, Integration Test
IT Comtor PHP, Python, Laravel, WordPress, Japanese
Bridge Software Engineer BrSE
Lead Java Engineer
Solution Architect
Cloud System Engineer GCP
Platform Engineer DevOps, AWS, Cloud
Data Engineer DBA
Automation Tester
Senior Java Developer
CV Quan tri Co so du lieu- Database Administrator
Middle/ Senior Site Reliability Engineer SRE/ DevOps
Senior Embedded SW Engineer VV  Chiplet
DevOps Engineer Nginx, English-speaking
Lead Android Engineer
Senior Scrum Master
Senior Software Engineer DevOps. NET, C#
Senior Application Operations Van hanh ung dung
Senior Network  Infrastructure Security Engineer
2D Animation Designer UI-UX, Games
Mid/Senior Backend Developer NodeJS, English
Senior Manager Japanese N2+
Mid/Senior Backend Developer .NET Core, C#, SQL
Hybrid - US Market Senior Fullstack .NET Developer
Senior Master Data Operations Analyst IM/MDM
Software/Technical Architect Cloud, AWS, Security
Product Owner Agile/Scrum/Squad, AI, API
Data Governance Analyst
Senior Security Operations Engineer
Machine Learning Engineer Python/AI
Senior QA Automation Lab Engineer
QA Automation Engineer, Embedded Video AI
QA Automation Technical Manager, Embedded Video AI
Senior Web Developer
 AI Architecture Lead
Penetration Tester
Principal Backend Engineer Big Data/ NodeJS
QC Engineer Manual, Automation Test
Senior Project Manager/Program Manager RTE
Principal QA Engineer/QA Engineering Manager
UI/UX Designer Middle
Junior/Middle Tester QA QC
Urgent - Bridge Software Engineer BrSE, AWS Cloud
SecOps Engineer
Senior AI Engineer Computer Vision/NPL/LLM
IT Service Management
AI Expert Deep Learning, Machine Learning
Chuyen Vien Phat Trien Khoa Hoc Du Lieu- Data Scientist
Senior AI Expert Deep Learning, Machine Learning
Jr. Fullstack .Net Developer ASP.NET, ReactJS, .NET 8
IT Support Engineer Cloud/ Networking
Cobol Developer French Speaking
Senior Salesforce Developer French speaking
Senior Tester
Frontend Dev React JS+Angular- Start afer Tet
Backend Engineer Go/Java - DOP
Middle/ Senior PHP Dev  AI/ MVC/ Laravel/ JavaScript
Senior Java Developer Spring Boot, SQL
Senior QA Engineer Automation Test, SQL, Python
QA QC Engineer Tester
Manual Tester Embedded, QA QC
Application Engineer TypeScript/ PHP
4 Senior Fullstack Engineer TypeScript/ReactJS/NextJS
AI Product Manager
Site Reliability Engineer DevOps/Cloud/.Net
Head of IT Business Partner
Mid/Senior Java Backend Developer English, Spring
Senior Data Analyst English, data science, fraud/risk
Sr Software Engineer, Machine Learning  AI, English
Senior Front-end React Developer Good English
Backend Engineer Java/Spring - Naver Care/Academic
Mobile Developer React Native/ IOS Swift  Join ASAP
Middle/Senior Java Engineer
IT Freshers 2026 Business Analyst, Devs, System
Project Manager Medical Device
02 Java Developer Spring
Data Engineer Power Platform / Databricks
Big Data Engineer
Software Engineer C#/.NET/ASP.NET
Senior Golang Dev/Tech Lead Go/English
Technical Demo Architect API, Javascript, JSON, Git
Project Manager Scrum Master/Agile/English - BONUS
Senior Backend Developer PHP, Laravel, MySQL, Kafka
Senior Software Engineer - Boomi
Game Server Developer
Senior PHP Developer Laravel / ReactJS / VueJS
AI Engineer/ Data Scientist Machine Learning/Python
Testing Manager QA QC/Tester/Banking
Test Architect QA QC, Tester, Playwright, Selenium
Senior IOS Mobile Apps Developer Remote, Swift
Android Developer Kotlin / MVVM
Middle Application TesterAI Model Platform Upto 1500
Senior Frontend Developer VueJS, ReactJS, Angular
Senior Solution Architect, API  System Integration
Ky su tri tue nhan tao AI/ML Engineering - K.CNTT
Chuyen gia Phan tich du lieu Senior Data Analyst
NodeJS Dev + ReactJS/NestJS/NextJS- Start after Tet
Expert Backend Engineer AWS, DevOps
Senior AI Engineer Agentic AI, MLOps
Vision Engineer C++, C#, Python
Mid-Senior Java Backend Developer Spring, English
VoiceAI Engineer LLM, NLP
Senior Oracle Database Administrator
Automation QA Engineer/Tester QA/QC, English
Product Manager E-commerce, upto 80,000/year
Database Engineer SQL Server
AI-Powered Full-Stack Developer
ServiceNow DECP Freshers - proficient in Javascript
Junior Backend Developer PHP/ NodeJS/ Ruby on Rails
Automation Tester DevOps, Selenium
GoLang Developer
Flutter Apps Developer Dart/iOS/Android/Windows
Android Developer Kotlin - Up to 45M
Business Process Specialist
Senior Unity Developer
Mid-level Backend Developer Golang,Java
Backend Engineer Golang, Python, NodeJS
Chuyen vien Quan ly du an - Project Manager PM
CV Tu Van Giai Phap/ Business Analyst Banking/Fintech
Application Developer .Net Core 6, C#, HTML, ReactJS
Java Developer in Test Senior/Mid-level, Good English
Full Stack Developer NodeJS, ReactJS, AI
AI Architecture Lead LLMs, AI APIs, Python, NodeJS
Senior Business Analyst Technical Analyst, English
Data  AI Scientist Python, SQL, GenAI
Frontend Engineer React.js, CSS - Hybrid
Full Stack Engineer Node.js, React - Hybrid
Product RD Manager
Senior Cloud Engineer AWS, GCP, English
IT Business Analyst Product
Senior Java Developer Spring Boot, MySQL, MongoDB
Senior Machine Learning Engineer
Director of Operations
Site Reliability Engineer SRE
System Engineer Python, Linux, Cloud, Networking
Windows Engineer C++
Java Engineer Spring, Junit From 3 Years
Chuyen vien DevOps Engineer Database, SQL
Senior Frontend Engineer ReactJS
Backend Engineer Golang/ Ruby on Rails
iOS Developer Swift
Front-end Developer
Senior .Net Backend Engineer -Up to 55K
Frontend Developer Reactjs/ VueJS - Di lam sau tet
Principal AI Architect English - Onboard after Tet
Solution Architect English
Middle Software Tester QA QC
Backend Developer Shopify, NestJS, Spring Boot, SQL
Android Developer
Product Owner Blockchain, Figma, English
Embedded Software Engineer
Odoo Developer Python
Project Manager Business Analyst/Agile/Scrum/Jira
Cybersecurity Engineer Security/API/Networking
Senior QC Engineer QA QC, Manual
AI Engineer LLM, Azure, Python, English
Business Analyst Japanese
Junior/ Middle Java Developer Spring Boot
SW Engineer Senior TypeScript, React Native, AI, LLM
English Scrum Master Middle/Senior
Sr/ Jr Backend Developers Golang / Java
Odoo Technical Leader Python, PostgreSQL
UI/UX Designer Blockchain/web3
Technical Lead
Remote UX/UI Designer - AI Product Enhancement
Senior Backend Java Engineer Spring, React
Remote -Sr. React Native Engineer ReactJS, Javascript
Embedded Developer C++
C# .NET Fullstack Jr to Sr Level
Tester QA/QC - Urgent
Junior QA Engineer
.NET Developer .NET Core, SQL
AI Computer Vision Engineer  eKYC Face Matching
Data Engineer SQL/NoSQL, AWS - CRM
Senior AWS Network Engineer
Site Reliability Engineer Azure, English
Head of BI
Senior DevOps Data Platform
Screen Design Leader N2, Photoshop
5 Senior Full-Stack Developer .NET/React
All level Network Administrator Cisco/HP/Juniper
Devops Engineer Cloud, AWS, Azure, CI/CD
3D Character  Item Designer 3ds Max
Chuyen Gia phat trien the Smart Vista - K.CNTT
JOB-40 Graphic Designer Junior
Backend Engineer .NET
Mobile Developer Flutter
Java Developer 10 headcounts
Oracle ERP Staff Operations  Extension Development
Ky Su Trien Khai He Thong System Solution Engineer
Fullstack Developer .Net, NodeJs, Angular
 Fullstack Developer Python/Django/JavaScrip
Junior Manual Tester QA QC
DevOps Engineer - Upto 3500 - Di lam sau TET
CV/CVCC/Chuyen gia Kien truc  Giai phap
IT Business Analyst English
Giam Doc cong nghe Cloud Cloud Engineering Manager
Database Administrator
Backend/ Cloud Engineer
Back End Python Developer Python, AWS
Network Operations Engineer NOC
Senior QA Automation Engineer Playwright, Java
GRC Engineer Risk Management/ Cybersecurity
Senior/Lead QA Automation EngineerPlaywright
Cloud Solution Architect AWS Senior, Junior
Data Engineer SQL/ Python/ Cloud
Database Developer DB/ETL/MS SQL
Odoo Functional Consultant ERP, Python, Agile
Backend Developer C++/Rust
ReactJS Developer
Data Engineer SQL, Python
Consulting Sales Manager / Sales Executive
AI Developer
NodeJS Developer AI Data Assistant Tools
Automation QC Engineer AI Data Cleansing Tool
 System Analyst Automation Test Knowledge
UI/UX Designer AI Data Integrity for SAP
Lead Data Engineer Azure, ETL
Software Project Manager  Japanese OR Chinese Speaking
Software Engineer Python, FastAPI ,React, JavaScript
Microsoft D365 FO Functional Consultant

In [ ]:
df['level'].unique()

array([None, 'Senior', 'Lead', 'Intern', 'Junior', 'Middle', 'Fresher',
       'Manager'], dtype=object)

In [ ]:
# Thiết lập hiển thị tối đa số cột và độ rộng
pd.set_option('display.max_columns', None)  # Không giới hạn số cột
pd.set_option('display.width', 2000)        # Tăng độ rộng hiển thị

# In ra 10 dòng đầu để kiểm tra
print(df.head(40))

       id                                              title                                       company_name                            location  source                                         source_url                                        description                                  requirements_text    job_type   level  salary_min  salary_max salary_currency                       salary_text  experience_years_min  experience_years_max education_level certifications                                    required_skills preferred_skills                                           benefits company_rating  is_remote  is_active           created_at           updated_at           crawled_at
0    3462                    Frontend developer (PA project)                                           CUBICASA                 Quận 1, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/frontend-develop...  Your role & responsibilities:\nWe’re looking f...  Your skills & qualifications:\n\nExperience in...   Full-time    None         NaN         NaN            None                        Negotiable                   1.0                   1.0            None           None  ["CSS", "HTML", "Git", "Restful Api", "SASS", ...             None  ["13th month bonusParticipate in large-scale a...           None          0        1.0  2026-01-11 15:11:56  2026-01-18 10:57:55  2026-01-11 15:11:56
8    3470             TIGER TRIBE – SENIOR BACKEND DEVELOPER                                        TIGER TRIBE                 Quận 1, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/tiger-tribe-seni...  Your role & responsibilities:\nDesign, develop...  Your skills & qualifications:\n\n5+ years of e...   Full-time  Senior         NaN         NaN            None                        Negotiable                   5.0                   5.0            None           None  ["ASP.NET", "C#", ".NET", "SQL Server", "Restf...             None  ["Fixed Bonus: 13th Variable Bonus: 1~3 months...           None          0        1.0  2026-01-11 15:12:27  2026-01-18 13:56:11  2026-01-11 15:12:27
16   3478  Lead Full-stack Developer (.NET, Angular/React...                                            EMESOFT          Quận Tân Bình, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/lead-full-stack-...  Your role & responsibilities:\nLeading the dev...  Your skills & qualifications:\n\nA Bachelor’s ...   Full-time    Lead         NaN         NaN            None                        Negotiable                   5.0                   5.0            None           None  ["C#", ".NET", "ReactJS", "Angular", ".NET Core"]             None  ["Salary in probation time: 100%", "Bonus: 13t...           None          0        1.0  2026-01-11 15:12:58  2026-01-18 13:56:12  2026-01-11 15:12:58
20   3482                APAC DATA HUB – SENIOR DATA SCIENCE                                        TIGER TRIBE                 Quận 1, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/apac-data-hub-se...  Your role & responsibilities:\nResponsible for...  Your skills & qualifications:\n\nBA/MSc in Sta...   Full-time  Senior         NaN         NaN            None                        Negotiable                   3.0                   3.0            None           None  ["Python", "Data Science", "Azure", "CI/CD", "...             None  ["Fixed Bonus: 13th Variable Bonus: 1~3 months...           None          0        1.0  2026-01-11 15:13:13  2026-01-18 13:56:12  2026-01-11 15:13:13
21   3483                          HRIS Technical Specialist   Ngân hàng TMCP Công Thương Việt Nam (Vietinbank)              Quận Hoàn Kiếm, Hà Nội  topdev  https://topdev.vn/detail-jobs/hris-technical-s...  Your roles & responsibilities:\n1. Work object...  Your skills & qualifications:\n\nTraining leve...   Full-time    None         NaN         NaN            None                        Negotiable                   1.0                   1.0            None           None                         ["Oracle", "PL/SQL", "AI"]             None  ["VietinBank's salary mechanism is built scien...           None          0        1.0  2026-01-11 15:13:17  2026-01-18 13:56:12  2026-01-11 15:13:17
26   3488  Senior QA Engineer (Creative & Development Tools)                          Sparx* - A Virtuos Studio  Thành phố Hồ Chí Minh, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/senior-qa-engine...  Your role & responsibilities:\nDefine and impl...  Your skills & qualifications:\n\nBachelor’s de...   Full-time  Senior         NaN         NaN            None                        Negotiable                   5.0                   5.0            None           None       ["QA", "Automation Tester", "Automation QA"]             None                                               None           None          0        1.0  2026-01-11 15:13:36  2026-01-18 13:56:13  2026-01-11 15:13:36
36   3498             Phân tích Nghiệp Vụ (Business Analyst)  NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN LỘC PHÁT VIỆT NAM...              Quận Hoàn Kiếm, Hà Nội  topdev  https://topdev.vn/detail-jobs/phan-tich-nghiep...  Your roles & responsibilities:\nResearch busin...  Your skills & qualifications:\n\nGraduated fro...   Full-time    None         NaN         NaN            None                        Negotiable                   5.0                   5.0            None           None               ["Business Analyst", "Core Banking"]             None  ["Bonuses on Holidays and New Year according t...           None          0        1.0  2026-01-11 15:14:14  2026-01-18 10:57:57  2026-01-11 15:14:14
45   3507    PHP 5Y+ – Sub Lead / Team Lead (Payment System)                                          TTR Group  Thành phố Hồ Chí Minh, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/php-5y-sub-lead-...  Your roles & responsibilities:\nJoin\n analysi...  Your skills & qualifications:\n\nRequired\n\n\...   Full-time    Lead  18000000.0  22000000.0             VND  18,000,000 VND to 22,000,000 VND                   4.0                   4.0            None           None                      ["PHP", "OOP", "Restful Api"]             None                                               None           None          0        1.0  2026-01-11 15:14:51  2026-01-18 13:56:16  2026-01-11 15:14:51
46   3508                    Senior Data Engineer (40000063)                                        Techcombank  Thành phố Hồ Chí Minh, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/senior-data-engi...  Your role & responsibilities:\nKey Accountabil...  Your skills & qualifications:\n\nQualification...   Full-time  Senior         NaN         NaN            None                        Negotiable                   5.0                   5.0            None           None  ["SQL", "Python", "Database", "Data Engineer",...             None  ["Competitive salary Two-month probationary pe...           None          1        1.0  2026-01-11 15:14:54  2026-01-18 13:56:16  2026-01-11 15:14:54
47   3509                 DEVOPS ENGINEER (Upto $2000 Gross)                               CÔNG TY TNHH AMBEROS          Quận Tân Bình, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/devops-engineer-...  Your role & responsibilities:\nKEY RESPONSIBIL...  Your skills & qualifications:\n\nMinimum 5+ ye...   Full-time    None         NaN         NaN            None                   Up to 2.000 USD                   5.0                   5.0            None           None                      ["Linux", "Python", "DevOps"]             None  ["Insurance & Healthcare: Social & health insu...           None          1        1.0  2026-01-11 15:14:58  2026-01-18 13:56:17  2026-01-11 15:14:58
52   3514            SENIOR JAVA DEVELOPER (Onboard sau tết)       CÔNG TY TNHH GIẢI PHÁP CÔNG NGHỆ THUẬN THÀNH            Thành phố Hà Nội, Hà Nội  topdev  https://topdev.vn/detail-jobs/senior-java-deve...  Your roles & responsibilities:\nParticipate in...  Your skills & qualifications:\n\nMore than 5 y...   Full-time  Senior         NaN         NaN            None              Up to 34.000.000 VND                   5.0                   5.0            None           None  ["Java", "Back-End", "Spring", "Database", "Ja...             None                                               None           None          0        1.0  2026-01-11 15:15:17  2026-01-18 13:56:17  2026-01-11 15:15:17
58   3520              TIGER TRIBE – MOBILE DEVELOPER INTERN                                        TIGER TRIBE                 Quận 1, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/tiger-tribe-mobi...  Your role & responsibilities:\nAssist in the d...  Your skills & qualifications:\n\nMajor in Comp...  Internship  Intern         NaN         NaN            None                        Negotiable                   NaN                   NaN            None           None  ["Agile", "Android", "iOS", "React Native", "S...             None  ["Fixed Bonus: 13th Variable Bonus: 1~3 months...           None          0        1.0  2026-01-11 15:15:41  2026-01-18 10:01:53  2026-01-11 15:15:41
72   3534                                          Junior QA                                     ST Engineering                 Quận 1, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/junior-qa-st-eng...  Your role & responsibilities:\nPerform manual ...  Your skills & qualifications:\n\n1–3 years of ...   Full-time  Junior         NaN         NaN            None              Up to 22.000.000 VND                   3.0                   3.0            None           None            ["QA", "Automation Tester", "Selenium"]             None  ["14 annual leaves 100% salary during probatio...           None          0        1.0  2026-01-11 15:16:40  2026-01-18 13:56:20  2026-01-11 15:16:40
73   3535  AI/NLP Engineer / Algorithm Engineer– Junior/M...                                           CAZOODLE                Quận Đống Đa, Hà Nội  topdev  https://topdev.vn/detail-jobs/ai-nlp-engineer-...  Your role & responsibilities:\nResearch and ap...  Your skills & qualifications:\n\nFrom 1+ years...   Full-time  Junior         NaN         NaN            None                        Negotiable                   1.0                   1.0            None           None                  ["Machine Learning", "API", "AI"]             None  ["Competitive compensation package with privat...           None          0        1.0  2026-01-11 15:16:44  2026-01-18 13:56:21  2026-01-11 15:16:44
74   3536                        AI ENGINEER (JUNIOR/MIDDLE)  Công Ty Cổ Phần Phát Hành Sách TP Hồ Chí Minh ...                 Quận 3, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/ai-engineer-juni...  Your roles & responsibilities:\nAnalyze busine...  Your skills & qualifications:\n\nExpertise and...   Full-time  Junior  10000000.0  40000000.0             VND  10,000,000 VND to 40,000,000 VND                   2.0                   2.0            None           None                    ["AI", "Tensorflow", "PyTorch"]             None  ["Insurance according to regulations", "Team b...           None          0        1.0  2026-01-11 15:16:47  2026-01-18 13:56:21  2026-01-11 15:16:47
80   3542                               VOIP System Engineer                                           NamiTech                 Quận 7, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/voip-system-engi...  Your role & responsibilities:\nBuild up integr...  Your skills & qualifications:\n\nAt least Bach...   Part-time    None         NaN         NaN            None                        Negotiable                   1.0                   1.0            None           None               ["Cisco", "System Engineer", "VoIP"]             None  ["Working hours: From Monday to Friday (9:00 t...           None          1        1.0  2026-01-11 15:17:11  2026-01-18 13:56:22  2026-01-11 15:17:11
81   3543    Automation Tester (Playwright, Selenium, QA/QC)                                      Ekino VietNam                Quận 11, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/automation-teste...  Your role & responsibilities:\nAs an Automatio...  Your skills & qualifications:\n\nKey Requireme...   Full-time    None         NaN         NaN            None                        Negotiable                   1.0                   1.0            None           None    ["JavaScript", "Automation Tester", "Selenium"]             None  ["Annual bonuses for year-end and achieved per...           None          0        1.0  2026-01-11 15:17:14  2026-01-18 13:56:22  2026-01-11 15:17:14
85   3547                      JUNIOR DEVELOPER (MOBILE APP)                                        Cathay Life                 Quận 1, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/junior-developer...  Your roles & responsibilities:\nDevelop and de...  Your skills & qualifications:\n\nGraduated fro...   Full-time  Junior         NaN         NaN            None                        Negotiable                   1.0                   1.0            None           None                   ["Swift", "JSON", "Restful Api"]             None  ["Social insurance & Other insurance/Social In...           None          0        1.0  2026-01-11 15:17:29  2026-01-18 13:56:23  2026-01-11 15:17:29
87   3549                                     Game 3D Artist                                  SUPERCENT VIETNAM                 Quận 3, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/game-3d-artist-s...  Your roles & responsibilities:\nJob Descriptio...  Your skills & qualifications:\n\nRequirements\...   Full-time    None         NaN         NaN            None                        Negotiable                   1.0                   1.0            None           None                ["Unity", "Photoshop", "3D Artist"]             None  ["100% salary during the probation period 13th...           None          1        1.0  2026-01-11 15:17:37  2026-01-18 13:56:23  2026-01-11 15:17:37
95   3557                                 Firmware Developer             Motorola Solutions, VietNam R&D Center      Thành phố Thủ Đức, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/firmware-develop...  Your role & responsibilities:\nDesign and impl...  Your skills & qualifications:\n\nGraduated fro...   Full-time    None      1400.0      1800.0             USD            1.400 USD to 1.800 USD                   7.0                   7.0            None           None                                       ["Firmware"]             None  ["Compensation & bonus: 13th & 14th salary, AI...           None          0        1.0  2026-01-11 15:18:05  2026-01-18 13:56:24  2026-01-11 15:18:05
96   3558                                        Senior Java                            CÔNG TY CỔ PHẦN HAIBAZO          Thành phố Đà Nẵng, Đà Nẵng  topdev  https://topdev.vn/detail-jobs/senior-java-cong...  Your role & responsibilities:\nDesign, develop...  Your skills & qualifications:\n\n5+ years of e...   Full-time  Senior         NaN         NaN            None              Up to 40.000.000 VND                   5.0                   5.0            None           None        ["Java", "Spring Boot", "Java Spring Boot"]             None                                               None           None          0        1.0  2026-01-11 15:18:09  2026-01-18 13:56:25  2026-01-11 15:18:09
99   3561                        PHP DEVELOPER - HO CHI MINH                                            Headway  Thành phố Hồ Chí Minh, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/php-developer-ho...  Your roles & responsibilities:\nBuild, develop...  Your skills & qualifications:\n\nGraduated fro...   Full-time    None         NaN         NaN            None                        Negotiable                   2.0                   2.0            None           None                   ["PHP", "JavaScript", "Laravel"]             None  ["Participate in social insurance, health insu...           None          0        1.0  2026-01-11 15:18:20  2026-01-18 13:56:25  2026-01-11 15:18:20
100  3562                             Java Software Engineer         CÔNG TY TNHH GIẢI PHÁP NHÂN SỰ GLOBAL DOOR  Thành phố Hồ Chí Minh, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/java-software-en...  Your roles & responsibilities:\nTogether with ...  Your skills & qualifications:\n\nHave 4 or mor...   Full-time    None      1000.0      1400.0             USD            1.000 USD to 1.400 USD                   4.0                   4.0            None           None                     ["Java", "HTML", "PostgreSql"]             None                                               None           None          0        1.0  2026-01-11 15:18:24  2026-01-18 13:56:25  2026-01-11 15:18:24
101  3563                                     JAVA Developer                                   POSCO DX Vietnam                 Quận 7, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/java-developer-p...  Your role & responsibilities:\nCollaborate wit...  Your skills & qualifications:\n\nMinimum \n3 y...   Full-time    None         NaN         NaN            None                        Negotiable                   3.0                   3.0            None           None         ["Java", "JavaScript", "Java Spring Boot"]             None  ["Professional, dynamic, friendly, and English...           None          0        1.0  2026-01-11 15:18:28  2026-01-18 13:56:25  2026-01-11 15:18:28
107  3569                               Middle PHP Developer      Công ty Cổ Phần Công Nghệ Giáo Dục Thành Phát               Quận Cầu Giấy, Hà Nội  topdev  https://topdev.vn/detail-jobs/middle-php-devel...  Your roles & responsibilities:\nDevelop API we...  Your skills & qualifications:\n\nRequired\n\n\...   Full-time  Middle  18000000.0  25000000.0             VND  18,000,000 VND to 25,000,000 VND                   1.0                   1.0            None           None                     ["PHP", "JavaScript", "MySQL"]             None  ["Opportunity to become a key member, Tech Lea...           None          0        1.0  2026-01-11 15:18:50  2026-01-18 13:56:27  2026-01-11 15:18:50
108  3570   Lập trình viên Angular (Làm Việc Thứ 2 –  Thứ 6)          CÔNG TY CỔ PHẦN ĐẦU TƯ VÀ CÔNG NGHỆ SOLID            Thành phố Hà Nội, Hà Nội  topdev  https://topdev.vn/detail-jobs/lap-trinh-vien-a...  Your roles & responsibilities:\nParticipate in...  Your skills & qualifications:\n\nGraduated fro...   Full-time    None         NaN         NaN            None              Up to 18.000.000 VND                   1.0                   1.0            None           None                    ["ReactJS", "VueJS", "Angular"]             None  ["Enjoy full benefits as prescribed by law: 12...           None          0        1.0  2026-01-11 15:18:54  2026-01-18 13:56:27  2026-01-11 15:18:54
111  3573                Technical Lead (Web & App Projects)                          CÔNG TY TNHH BANTAM POINT          Quận Ngũ Hành Sơn, Đà Nẵng  topdev  https://topdev.vn/detail-jobs/technical-lead-w...  Your role & responsibilities:\nTechnical Strat...  Your skills & qualifications:\n\nExperience & ...    Contract    Lead         NaN         NaN            None                        Negotiable                   2.0                   2.0            None           None          ["PHP", "JavaScript", "Technical Leader"]             None  ["Annual salary review. Annual health check. S...           None          0        1.0  2026-01-11 15:19:05  2026-01-18 13:56:27  2026-01-11 15:19:05

**Điền education_level từ requirements_text**

In [ ]:
df['education_level'].unique()

array([None, "Bachelor's Degree", 'PhD', "Master's Degree",
       "Associate's Degree"], dtype=object)

In [ ]:
EDU_MAP = {
    "Bachelor's Degree": "Bachelor",
    "Master's Degree": "Master",
    "Associate's Degree": "Associate",
    "PhD": "PhD",
    "Doctorate": "PhD"
}

def extract_education_level(row):
    # 0. NẾU ĐÃ CÓ education_level → CHUẨN HÓA RỒI GIỮ
    edu = row['education_level']
    if pd.notna(edu) and str(edu).strip() != '':
        return EDU_MAP.get(edu, edu)

    # 1. Gộp text
    text = (str(row['requirements_text']) + " " + str(row['description'])).lower()

    if not text.strip() or text in ['none', 'nan']:
        return None

    # 2. PhD
    if re.search(r'\b(phd|ph\.d|doctorate|doctor of philosophy)\b', text):
        return 'PhD'

    # 3. Master
    if re.search(r'\b(master|ms|msc|mba|master degree)\b', text):
        return 'Master'

    # 4. Bachelor
    bachelor_patterns = [
        r'\b(bachelor|bs|bsc|ba|b\.s|b\.sc)\b',
        r'\buniversity\s+degree\b',
        r'\bdegree\s+in\s+(cs|it|software|computer|engineering)\b',
        r'\bgraduate\b'
    ]
    if any(re.search(p, text) for p in bachelor_patterns):
        return 'Bachelor'

    # 5. Associate
    if re.search(r'\bassociate|associate degree\b', text):
        return 'Associate'

    return 'Other'

# --- THỰC THI ---
df['education_level'] = df.apply(extract_education_level, axis=1)

# Kiểm tra kết quả
print(df['education_level'].value_counts())

education_level
Other        5469
Bachelor     2906
Master       1483
PhD           346
Associate     235
Name: count, dtype: int64

In [ ]:
df['level'].isnull().sum() # đếm giá trị thiếu

np.int64(7154)

**Điền required_skills từ requirements_text**

In [ ]:
df['required_skills'].isnull().sum() # đếm giá trị thiếu

np.int64(2328)

In [ ]:
skill_library = [
    'Python', 'Java', 'C++', 'C#', '.NET', 'ASP.NET', 'JavaScript', 'TypeScript', 'React', 'Angular', 'Vue',
    'Node.js', 'PHP', 'Laravel', 'SQL', 'MySQL', 'PostgreSQL', 'MongoDB', 'NoSQL', 'AWS', 'Azure', 'GCP',
    'Docker', 'Kubernetes', 'Jenkins', 'CI/CD', 'Git', 'Flutter', 'React Native', 'Swift', 'Kotlin',
    'Spring Boot', 'Go', 'Golang', 'Ruby', 'Rails', 'Unity', 'HTML', 'CSS', 'Tailwind', 'Bootstrap',
    'Hadoop', 'Spark', 'Machine Learning', 'AI', 'NLP', 'Data Science', 'Tableau', 'Power BI'
]

def extract_skills(row):
    # 1. Nếu đã có required_skills → GIỮ NGUYÊN
    if pd.notna(row['required_skills']) and str(row['required_skills']).strip() not in ['', '[]']:
        return row['required_skills']

    # 2. Nếu không có thì mới trích xuất
    text = str(row['requirements_text']).lower()
    if not text or text == 'none':
        return None

    found_skills = []
    for skill in skill_library:
        pattern = rf'\b{re.escape(skill.lower())}\b'
        if re.search(pattern, text):
            found_skills.append(skill)

    return ", ".join(found_skills) if found_skills else None


# --- THỰC THI ---
df['required_skills'] = df.apply(extract_skills, axis=1)

In [ ]:
df['required_skills'].isnull().sum() # đếm giá trị thiếu

np.int64(2413)

In [ ]:
print(df.head(20))

      id                                              title                                       company_name                            location  source                                         source_url                                        description                                  requirements_text    job_type   level  salary_min  salary_max salary_currency                       salary_text  experience_years_min  experience_years_max education_level certifications                                    required_skills preferred_skills                                           benefits company_rating  is_remote  is_active           created_at           updated_at           crawled_at
0   3462                    Frontend developer (PA project)                                           CUBICASA                 Quận 1, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/frontend-develop...  Your role & responsibilities:\nWe’re looking f...  Your skills & qualifications:\n\nExperience in...   Full-time    None         NaN         NaN            None                        Negotiable                   1.0                   1.0           Other           None  ["CSS", "HTML", "Git", "Restful Api", "SASS", ...             None  ["13th month bonusParticipate in large-scale a...           None          0        1.0  2026-01-11 15:11:56  2026-01-18 10:57:55  2026-01-11 15:11:56
8   3470             TIGER TRIBE – SENIOR BACKEND DEVELOPER                                        TIGER TRIBE                 Quận 1, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/tiger-tribe-seni...  Your role & responsibilities:\nDesign, develop...  Your skills & qualifications:\n\n5+ years of e...   Full-time  Senior         NaN         NaN            None                        Negotiable                   5.0                   5.0           Other           None  ["ASP.NET", "C#", ".NET", "SQL Server", "Restf...             None  ["Fixed Bonus: 13th Variable Bonus: 1~3 months...           None          0        1.0  2026-01-11 15:12:27  2026-01-18 13:56:11  2026-01-11 15:12:27
16  3478  Lead Full-stack Developer (.NET, Angular/React...                                            EMESOFT          Quận Tân Bình, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/lead-full-stack-...  Your role & responsibilities:\nLeading the dev...  Your skills & qualifications:\n\nA Bachelor’s ...   Full-time    Lead         NaN         NaN            None                        Negotiable                   5.0                   5.0          Master           None  ["C#", ".NET", "ReactJS", "Angular", ".NET Core"]             None  ["Salary in probation time: 100%", "Bonus: 13t...           None          0        1.0  2026-01-11 15:12:58  2026-01-18 13:56:12  2026-01-11 15:12:58
20  3482                APAC DATA HUB – SENIOR DATA SCIENCE                                        TIGER TRIBE                 Quận 1, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/apac-data-hub-se...  Your role & responsibilities:\nResponsible for...  Your skills & qualifications:\n\nBA/MSc in Sta...   Full-time  Senior         NaN         NaN            None                        Negotiable                   3.0                   3.0          Master           None  ["Python", "Data Science", "Azure", "CI/CD", "...             None  ["Fixed Bonus: 13th Variable Bonus: 1~3 months...           None          0        1.0  2026-01-11 15:13:13  2026-01-18 13:56:12  2026-01-11 15:13:13
21  3483                          HRIS Technical Specialist   Ngân hàng TMCP Công Thương Việt Nam (Vietinbank)              Quận Hoàn Kiếm, Hà Nội  topdev  https://topdev.vn/detail-jobs/hris-technical-s...  Your roles & responsibilities:\n1. Work object...  Your skills & qualifications:\n\nTraining leve...   Full-time    None         NaN         NaN            None                        Negotiable                   1.0                   1.0        Bachelor           None                         ["Oracle", "PL/SQL", "AI"]             None  ["VietinBank's salary mechanism is built scien...           None          0        1.0  2026-01-11 15:13:17  2026-01-18 13:56:12  2026-01-11 15:13:17
26  3488  Senior QA Engineer (Creative & Development Tools)                          Sparx* - A Virtuos Studio  Thành phố Hồ Chí Minh, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/senior-qa-engine...  Your role & responsibilities:\nDefine and impl...  Your skills & qualifications:\n\nBachelor’s de...   Full-time  Senior         NaN         NaN            None                        Negotiable                   5.0                   5.0        Bachelor           None       ["QA", "Automation Tester", "Automation QA"]             None                                               None           None          0        1.0  2026-01-11 15:13:36  2026-01-18 13:56:13  2026-01-11 15:13:36
36  3498             Phân tích Nghiệp Vụ (Business Analyst)  NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN LỘC PHÁT VIỆT NAM...              Quận Hoàn Kiếm, Hà Nội  topdev  https://topdev.vn/detail-jobs/phan-tich-nghiep...  Your roles & responsibilities:\nResearch busin...  Your skills & qualifications:\n\nGraduated fro...   Full-time    None         NaN         NaN            None                        Negotiable                   5.0                   5.0           Other           None               ["Business Analyst", "Core Banking"]             None  ["Bonuses on Holidays and New Year according t...           None          0        1.0  2026-01-11 15:14:14  2026-01-18 10:57:57  2026-01-11 15:14:14
45  3507    PHP 5Y+ – Sub Lead / Team Lead (Payment System)                                          TTR Group  Thành phố Hồ Chí Minh, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/php-5y-sub-lead-...  Your roles & responsibilities:\nJoin\n analysi...  Your skills & qualifications:\n\nRequired\n\n\...   Full-time    Lead  18000000.0  22000000.0             VND  18,000,000 VND to 22,000,000 VND                   4.0                   4.0           Other           None                      ["PHP", "OOP", "Restful Api"]             None                                               None           None          0        1.0  2026-01-11 15:14:51  2026-01-18 13:56:16  2026-01-11 15:14:51
46  3508                    Senior Data Engineer (40000063)                                        Techcombank  Thành phố Hồ Chí Minh, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/senior-data-engi...  Your role & responsibilities:\nKey Accountabil...  Your skills & qualifications:\n\nQualification...   Full-time  Senior         NaN         NaN            None                        Negotiable                   5.0                   5.0          Master           None  ["SQL", "Python", "Database", "Data Engineer",...             None  ["Competitive salary Two-month probationary pe...           None          1        1.0  2026-01-11 15:14:54  2026-01-18 13:56:16  2026-01-11 15:14:54
47  3509                 DEVOPS ENGINEER (Upto $2000 Gross)                               CÔNG TY TNHH AMBEROS          Quận Tân Bình, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/devops-engineer-...  Your role & responsibilities:\nKEY RESPONSIBIL...  Your skills & qualifications:\n\nMinimum 5+ ye...   Full-time    None         NaN         NaN            None                   Up to 2.000 USD                   5.0                   5.0           Other           None                      ["Linux", "Python", "DevOps"]             None  ["Insurance & Healthcare: Social & health insu...           None          1        1.0  2026-01-11 15:14:58  2026-01-18 13:56:17  2026-01-11 15:14:58
52  3514            SENIOR JAVA DEVELOPER (Onboard sau tết)       CÔNG TY TNHH GIẢI PHÁP CÔNG NGHỆ THUẬN THÀNH            Thành phố Hà Nội, Hà Nội  topdev  https://topdev.vn/detail-jobs/senior-java-deve...  Your roles & responsibilities:\nParticipate in...  Your skills & qualifications:\n\nMore than 5 y...   Full-time  Senior         NaN         NaN            None              Up to 34.000.000 VND                   5.0                   5.0           Other           None  ["Java", "Back-End", "Spring", "Database", "Ja...             None                                               None           None          0        1.0  2026-01-11 15:15:17  2026-01-18 13:56:17  2026-01-11 15:15:17
58  3520              TIGER TRIBE – MOBILE DEVELOPER INTERN                                        TIGER TRIBE                 Quận 1, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/tiger-tribe-mobi...  Your role & responsibilities:\nAssist in the d...  Your skills & qualifications:\n\nMajor in Comp...  Internship  Intern         NaN         NaN            None                        Negotiable                   NaN                   NaN           Other           None  ["Agile", "Android", "iOS", "React Native", "S...             None  ["Fixed Bonus: 13th Variable Bonus: 1~3 months...           None          0        1.0  2026-01-11 15:15:41  2026-01-18 10:01:53  2026-01-11 15:15:41
72  3534                                          Junior QA                                     ST Engineering                 Quận 1, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/junior-qa-st-eng...  Your role & responsibilities:\nPerform manual ...  Your skills & qualifications:\n\n1–3 years of ...   Full-time  Junior         NaN         NaN            None              Up to 22.000.000 VND                   3.0                   3.0           Other           None            ["QA", "Automation Tester", "Selenium"]             None  ["14 annual leaves 100% salary during probatio...           None          0        1.0  2026-01-11 15:16:40  2026-01-18 13:56:20  2026-01-11 15:16:40
73  3535  AI/NLP Engineer / Algorithm Engineer– Junior/M...                                           CAZOODLE                Quận Đống Đa, Hà Nội  topdev  https://topdev.vn/detail-jobs/ai-nlp-engineer-...  Your role & responsibilities:\nResearch and ap...  Your skills & qualifications:\n\nFrom 1+ years...   Full-time  Junior         NaN         NaN            None                        Negotiable                   1.0                   1.0           Other           None                  ["Machine Learning", "API", "AI"]             None  ["Competitive compensation package with privat...           None          0        1.0  2026-01-11 15:16:44  2026-01-18 13:56:21  2026-01-11 15:16:44
74  3536                        AI ENGINEER (JUNIOR/MIDDLE)  Công Ty Cổ Phần Phát Hành Sách TP Hồ Chí Minh ...                 Quận 3, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/ai-engineer-juni...  Your roles & responsibilities:\nAnalyze busine...  Your skills & qualifications:\n\nExpertise and...   Full-time  Junior  10000000.0  40000000.0             VND  10,000,000 VND to 40,000,000 VND                   2.0                   2.0           Other           None                    ["AI", "Tensorflow", "PyTorch"]             None  ["Insurance according to regulations", "Team b...           None          0        1.0  2026-01-11 15:16:47  2026-01-18 13:56:21  2026-01-11 15:16:47
80  3542                               VOIP System Engineer                                           NamiTech                 Quận 7, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/voip-system-engi...  Your role & responsibilities:\nBuild up integr...  Your skills & qualifications:\n\nAt least Bach...   Part-time    None         NaN         NaN            None                        Negotiable                   1.0                   1.0        Bachelor           None               ["Cisco", "System Engineer", "VoIP"]             None  ["Working hours: From Monday to Friday (9:00 t...           None          1        1.0  2026-01-11 15:17:11  2026-01-18 13:56:22  2026-01-11 15:17:11
81  3543    Automation Tester (Playwright, Selenium, QA/QC)                                      Ekino VietNam                Quận 11, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/automation-teste...  Your role & responsibilities:\nAs an Automatio...  Your skills & qualifications:\n\nKey Requireme...   Full-time    None         NaN         NaN            None                        Negotiable                   1.0                   1.0           Other           None    ["JavaScript", "Automation Tester", "Selenium"]             None  ["Annual bonuses for year-end and achieved per...           None          0        1.0  2026-01-11 15:17:14  2026-01-18 13:56:22  2026-01-11 15:17:14
85  3547                      JUNIOR DEVELOPER (MOBILE APP)                                        Cathay Life                 Quận 1, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/junior-developer...  Your roles & responsibilities:\nDevelop and de...  Your skills & qualifications:\n\nGraduated fro...   Full-time  Junior         NaN         NaN            None                        Negotiable                   1.0                   1.0          Master           None                   ["Swift", "JSON", "Restful Api"]             None  ["Social insurance & Other insurance/Social In...           None          0        1.0  2026-01-11 15:17:29  2026-01-18 13:56:23  2026-01-11 15:17:29
87  3549                                     Game 3D Artist                                  SUPERCENT VIETNAM                 Quận 3, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/game-3d-artist-s...  Your roles & responsibilities:\nJob Descriptio...  Your skills & qualifications:\n\nRequirements\...   Full-time    None         NaN         NaN            None                        Negotiable                   1.0                   1.0           Other           None                ["Unity", "Photoshop", "3D Artist"]             None  ["100% salary during the probation period 13th...           None          1        1.0  2026-01-11 15:17:37  2026-01-18 13:56:23  2026-01-11 15:17:37
95  3557                                 Firmware Developer             Motorola Solutions, VietNam R&D Center      Thành phố Thủ Đức, Hồ Chí Minh  topdev  https://topdev.vn/detail-jobs/firmware-develop...  Your role & responsibilities:\nDesign and impl...  Your skills & qualifications:\n\nGraduated fro...   Full-time    None      1400.0      1800.0             USD            1.400 USD to 1.800 USD                   7.0                   7.0           Other           None                                       ["Firmware"]             None  ["Compensation & bonus: 13th & 14th salary, AI...           None          0        1.0  2026-01-11 15:18:05  2026-01-18 13:56:24  2026-01-11 15:18:05

In [ ]:
df.drop(columns=['salary_min',
                 'salary_max', 'salary_currency',
                 'salary_text','company_rating',
                 'created_at', 'updated_at','crawled_at','preferred_skills',
                 'experience_years_max',
                 'experience_years_min'
                 ],
         inplace=True
        )

**điền level từ title**

In [ ]:
df['level'].unique()

array([None, 'Senior', 'Lead', 'Intern', 'Junior', 'Middle', 'Fresher',
       'Manager'], dtype=object)

In [ ]:
level_mapping = {
    # INTERN
    'intern': 'Intern', 'internship': 'Intern', 'thực tập sinh': 'Intern',

    # ENTRY / GRADUATE
    'entry': 'Entry', 'seniority levelentry level': 'Entry',
    'graduate': 'Entry', 'fresher': 'Entry',

    # JUNIOR
    'junior': 'Junior', 'jr': 'Junior',

    # MID / ASSOCIATE
    'mid': 'Mid', 'middle': 'Mid', 'seniority levelassociate': 'Mid',
    'associate': 'Mid', 'intermediate': 'Mid',

    # SENIOR
    'senior': 'Senior', 'sr': 'Senior', 'seniority levelmid senior level': 'Senior',

    # Gộp STAFF / PRINCIPAL vào chung với Senior
    'staff': 'Senior', 'principal': 'Senior', 'specialist': 'Senior',

    # LEAD
    'lead': 'Lead', 'leader': 'Lead', 'team lead': 'Lead', 'head': 'Lead',

    # MANAGER
    'manager': 'Manager', 'mgr': 'Manager', 'quản lý': 'Manager',

    # DIRECTOR / EXECUTIVE
    'director': 'Director', 'seniority leveldirector': 'Director',
    'executive': 'Executive', 'seniority levelexecutive': 'Executive',
    'vp': 'Executive', 'vice president': 'Executive', 'ceo': 'Executive', 'cto': 'Executive'
}
def extract_and_normalize_level(row):
    # Lấy dữ liệu từ 2 cột
    current_level = str(row['level']).lower().strip() if row['level'] else ""
    title = str(row['title']).lower() if row['title'] else ""

    # BƯỚC 1: Nếu cột level đã có dữ liệu, ưu tiên chuẩn hóa nó trước
    if current_level and current_level != 'none' and current_level != 'nan':
        for key, formal_name in level_mapping.items():
            if key in current_level:
                return formal_name

    # BƯỚC 2: Nếu level trống, trích xuất từ Title bằng Regex
    # Định nghĩa các từ khóa tìm kiếm trong Title (thứ tự ưu tiên từ cao xuống thấp)
    search_patterns = [
        ('intern', 'Intern'),
        ('fresher|graduate', 'Entry'),
        ('junior|jr', 'Junior'),
        ('senior|sr', 'Senior'),
        ('lead|leader|head', 'Lead'),
        ('principal|staff', 'Senior'),
        ('manager|mgr', 'Manager'),
        ('director', 'Director'),
        ('executive|vp|vice president|ceo|cto', 'Executive'),
        ('associate|intermediate', 'Mid'), # Thường là Mid
    ]

    for pattern, formal_name in search_patterns:
        # Sử dụng \b để tìm đúng từ độc lập (không bắt nhầm 'leadership' thành 'lead')
        if re.search(rf'\b({pattern})\b', title):
            return formal_name

    # BƯỚC 3: Nếu vẫn không tìm thấy, có thể gán là 'Unknown' hoặc 'Mid' tùy nhu cầu
    return 'Other'

In [ ]:
df["level"] = df.apply(extract_and_normalize_level, axis=1)

In [ ]:
df['level'].unique()

array(['Other', 'Senior', 'Lead', 'Intern', 'Junior', 'Mid', 'Entry',
       'Manager', 'Executive'], dtype=object)

In [ ]:
df['level'].isnull().sum() # đếm giá trị thiếu

np.int64(0)

**level: Mã hóa dạng thứ tự (Ordinal Encoding): Intern=0, Junior=1, Middle=2, Senior=3...
**

In [ ]:
LEVEL_MAPPING = {
    "intern": 0,
    "entry": 1,
    "junior": 2,
    "mid": 3,
    "senior": 4,
    "lead": 5,
    "manager": 6,
    "executive": 7,
    "other": 8
}

In [ ]:
def normalize_level(x):
    if pd.isna(x):
        return "other"
    return str(x).strip().lower()

In [ ]:
df["level_norm"] = df["level"].apply(normalize_level)
df["level_coding"] = df["level_norm"].map(LEVEL_MAPPING)
df[["level", "level_coding"]].head(30)

      level  level_coding
0     Other             8
8    Senior             4
16     Lead             5
20   Senior             4
21    Other             8
26   Senior             4
36    Other             8
45     Lead             5
46   Senior             4
47    Other             8
52   Senior             4
58   Intern             0
72   Junior             2
73   Junior             2
74   Junior             2
80    Other             8
81    Other             8
85   Junior             2
87    Other             8
95    Other             8
96   Senior             4
99    Other             8
100   Other             8
101   Other             8
107     Mid             3
108   Other             8
111    Lead             5
112   Other             8
114  Senior             4
115   Other             8

**In dữ liệu vào db**

In [ ]:

conn = sqlite3.connect("jobs_cleaned.db")

df.to_sql(
    name="jobs",
    con=conn,
    if_exists="replace",
    index=False
)

conn.close()

In [ ]:
!pip install pymysql

import sqlite3
import pandas as pd
from sqlalchemy import create_engine

# 1. Đọc từ SQLite
sqlite_conn = sqlite3.connect("jobs_cleaned.db")
df = pd.read_sql("SELECT * FROM jobs", sqlite_conn)

# 2. Kết nối TiDB (MySQL-compatible) với SSL
engine = create_engine(
    "mysql+pymysql://4GJhpnEevqoZfyD.root:oiK2dgnVVJLVHL4v@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/data-mining",
    connect_args={
        "ssl": {"ssl-mode": "REQUIRED"}
    }
)

# 3. Ghi sang TiDB
df.to_sql(
    name="jobs_cleaned",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=1000,
    method="multi"
)

sqlite_conn.close()

Requirement already satisfied: pymysql in /usr/local/lib/python3.12/dist-packages (1.1.2)

**Đánh độ thành thạo của required_skills**

In [ ]:
connect = sqlite3.connect("jobs_cleaned.db")

In [ ]:
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", connect)
print("Các bảng có trong file:", tables)

Các bảng có trong file:    name
0  jobs

In [ ]:
df_test = pd.read_sql("SELECT * FROM jobs ORDER BY RANDOM() LIMIT 30", connect)

In [ ]:
df_test["required_skills"].head(30)

0     "[\"AWS\", \"Azure\", \"CI/CD\", \"DevOps\", \...
1     "[\"Azure\", \"CI/CD\", \"GCP\", \"Git\", \"Py...
2                                            "[\"AI\"]"
3     "[\"AI\", \"Data Science\", \"Machine Learning...
4                                        "[\"Python\"]"
5                         Python, TypeScript, React, AI
6     ["Java", "Python", "JavaScript", "Ruby", "PHP"...
7     "[\"Agile\", \"Angular\", \"CI/CD\", \"DevOps\...
8     ["2 years of experience", "College or higher",...
9     "[\"AI\", \"AWS\", \"CI/CD\", \"Data Science\"...
10    "[\"AWS\", \"Agile\", \"CI/CD\", \"Docker\", \...
11                               "[\"AWS\", \"Azure\"]"
12               "[\"Angular\", \"DevOps\", \"scala\"]"
13    "[\"AI\", \"AWS\", \"Azure\", \"CI/CD\", \"Doc...
14                                  JavaScript, Angular
15    ["5 years of experience", "University and abov...
16                                                 None
17    ["Java", "Python", "JavaScript", "Ruby", "PHP"...
18                                                 None
19                                                 None
20    "[\"Azure\", \"Docker\", \"GitHub\", \"Go\", \...
21    ["3 years of experience", "University and abov...
22                                                 None
23                                        "[\"agile\"]"
24    "[\"AI\", \"Agile\", \"Angular\", \"Azure\", \...
25                                                 None
26                                                 None
27    ["Java", "Python", "JavaScript", "Ruby", "PHP"...
28                                                 None
29                                                 None
Name: required_skills, dtype: object

In [ ]:
x = df_test.loc[8, "required_skills"]
print(x)
print(type(x))

["2 years of experience", "College or higher", "Age 22 - 35", "Nam", "Fluent English communication", "Rest Saturday", "Social insurance", "Health insurance", "IT Helpdesk/IT support", "IT - Hardware and computers"]
<class 'str'>

In [ ]:
df_test['required_skills'].dtype

dtype('O')

In [ ]:
df_test.shape
df_test.columns

Index(['id', 'title', 'company_name', 'location', 'source', 'source_url', 'description', 'requirements_text', 'job_type', 'level', 'education_level', 'certifications', 'required_skills', 'benefits', 'is_remote', 'is_active', 'level_norm', 'level_coding'], dtype='object')

In [ ]:
# Parse required_skills (JSON LIST)
def normalize_skills(skills):
    """
    Xử lý cả:
    - JSON list dạng string: '["CSS","Git","Figma"]'
    - Python list: ['CSS','Git','Figma']
    - Chuỗi thường: 'CSS, Git, Figma'
    Output: ['css','git','figma']
    """
    if pd.isna(skills):
        return []

    # CASE 1: đã là list
    if isinstance(skills, list):
        return [
            s.strip().lower()
            for s in skills
            if isinstance(s, str)
        ]

    # CASE 2: là string
    if isinstance(skills, str):
        skills = skills.strip()

        # thử parse JSON
        if skills.startswith("["):
            try:
                parsed = json.loads(skills)
                if isinstance(parsed, list):
                    return [
                        s.strip().lower()
                        for s in parsed
                        if isinstance(s, str)
                    ]
            except:
                pass

        # fallback: comma-separated string
        return [
            s.strip().lower()
            for s in skills.split(",")
            if s.strip()
        ]

    return []

In [ ]:
df_test["required_skills"] = df_test["required_skills"].apply(normalize_skills)
df_test["required_skills"].head(30)

0     ["[\"aws\", \"azure\", \"ci/cd\", \"devops\", ...
1     ["[\"azure\", \"ci/cd\", \"gcp\", \"git\", \"p...
2                                          ["[\"ai\"]"]
3     ["[\"ai\", \"data science\", \"machine learnin...
4                                      ["[\"python\"]"]
5                       [python, typescript, react, ai]
6     [java, python, javascript, ruby, php, kotlin, ...
7     ["[\"agile\", \"angular\", \"ci/cd\", \"devops...
8     [2 years of experience, college or higher, age...
9     ["[\"ai\", \"aws\", \"ci/cd\", \"data science\...
10    ["[\"aws\", \"agile\", \"ci/cd\", \"docker\", ...
11                             ["[\"aws\", \"azure\"]"]
12             ["[\"angular\", \"devops\", \"scala\"]"]
13    ["[\"ai\", \"aws\", \"azure\", \"ci/cd\", \"do...
14                                [javascript, angular]
15    [5 years of experience, university and above, ...
16                                                   []
17    [java, python, javascript, ruby, php, spring, ...
18                                                   []
19                                                   []
20    ["[\"azure\", \"docker\", \"github\", \"go\", ...
21    [3 years of experience, university and above, ...
22                                                   []
23                                      ["[\"agile\"]"]
24    ["[\"ai\", \"agile\", \"angular\", \"azure\", ...
25                                                   []
26                                                   []
27    [java, python, javascript, ruby, php, ci/cd, m...
28                                                   []
29                                                   []
Name: required_skills, dtype: object

In [ ]:
for i in range(5):
    x = df_test.loc[i, "required_skills"]
    print(i, x, type(x))

0 ['"[\\"aws\\"', '\\"azure\\"', '\\"ci/cd\\"', '\\"devops\\"', '\\"gcp\\"', '\\"kubernetes\\"', '\\"python\\"]"'] <class 'list'>
1 ['"[\\"azure\\"', '\\"ci/cd\\"', '\\"gcp\\"', '\\"git\\"', '\\"python\\"', '\\"spark\\"]"'] <class 'list'>
2 ['"[\\"ai\\"]"'] <class 'list'>
3 ['"[\\"ai\\"', '\\"data science\\"', '\\"machine learning\\"', '\\"pytorch\\"', '\\"python\\"', '\\"agile\\"', '\\"machine learning\\"]"'] <class 'list'>
4 ['"[\\"python\\"]"'] <class 'list'>

In [ ]:
# Gộp text + normalize
import re

def safe_str(x):
    return "" if pd.isna(x) else str(x)

def normalize_text(text):
    text = text.lower()
    text = re.sub(r"\s+", " ", text)
    return text.strip()

df_test["full_text"] = (
    df_test["title"].apply(safe_str) + " . " +
    df_test["description"].apply(safe_str) + " . " +
    df_test["requirements_text"].apply(safe_str)
)

df_test["full_text_norm"] = df_test["full_text"].apply(normalize_text)

In [ ]:
# Keyword MẠNH / YẾU

STRONG_KWS = [
    "must have", "required", "strong", "solid",
    "proficient", "expert", "hands-on",
    "at least", "years of experience",
    "thành thạo", "bắt buộc", "yêu cầu", "chuyên sâu", "vững"
]

WEAK_KWS = [
    "nice to have", "plus", "preferred",
    "optional", "familiar", "basic",
    "ưu tiên", "là lợi thế", "bonus", "không bắt buộc"
]

In [ ]:
def get_skill_pattern(skill):
    """
    Tạo regex an toàn cho skill có thể có khoảng trắng
    ví dụ: 'code review', 'machine learning'
    """
    skill = skill.lower().strip()

    # escape các ký tự đặc biệt
    skill = re.escape(skill)

    # match cả cụm từ
    return rf"\b{skill}\b"

In [ ]:
# gán level 0 1
def assign_level(text_norm, skill, window=80):
    pat = get_skill_pattern(skill)

    for m in re.finditer(pat, text_norm):
        start = max(0, m.start() - window)
        end = min(len(text_norm), m.end() + window)
        context = text_norm[start:end]

        if any(k in context for k in STRONG_KWS):
            return 1
        if any(k in context for k in WEAK_KWS):
            return 0

    return 0

In [ ]:
# Tạo vocabulary skill
ALL_SKILLS = sorted({
    s.strip().lower()
    for skills in df_test["required_skills"]
    for s in skills
})

ALL_SKILLS

['"[\\"agile\\"',
 '"[\\"agile\\"]"',
 '"[\\"ai\\"',
 '"[\\"ai\\"]"',
 '"[\\"angular\\"',
 '"[\\"aws\\"',
 '"[\\"azure\\"',
 '"[\\"python\\"]"',
 '2 years of experience',
 '3 years of experience',
 '5 years of experience',
 '\\"agile\\"',
 '\\"angular\\"',
 '\\"aws\\"',
 '\\"azure\\"',
 '\\"azure\\"]"',
 '\\"ci/cd\\"',
 '\\"data science\\"',
 '\\"data science\\"]"',
 '\\"devops\\"',
 '\\"docker\\"',
 '\\"docker\\"]"',
 '\\"elasticsearch\\"',
 '\\"gcp\\"',
 '\\"gcp\\"]"',
 '\\"git\\"',
 '\\"github\\"',
 '\\"go\\"',
 '\\"java\\"',
 '\\"javascript\\"',
 '\\"jenkins\\"',
 '\\"kotlin\\"',
 '\\"kubernetes\\"',
 '\\"machine learning\\"',
 '\\"machine learning\\"]"',
 '\\"microservices\\"',
 '\\"microservices\\"]"',
 '\\"node.js\\"',
 '\\"postgresql\\"',
 '\\"python\\"',
 '\\"python\\"]"',
 '\\"pytorch\\"',
 '\\"react\\"',
 '\\"scala\\"]"',
 '\\"scrum\\"',
 '\\"spark\\"]"',
 '\\"spring\\"',
 '\\"vue.js\\"',
 'age 22 - 35',
 'agile',
 'ai',
 'android',
 'angular',
 'api',
 'aws',
 'bank',
 'business analyst (business analysis)',
 'ci/cd',
 'college or higher',
 'devops',
 'embedded engineer/embedded programmer',
 'engineering technology',
 'english reading comprehension',
 'finance',
 'fluent english communication',
 'gcp',
 'graphql',
 'health insurance',
 'ios',
 'it - hardware and computers',
 'it - software',
 'it helpdesk/it support',
 'java',
 'javascript',
 'kotlin',
 'linux',
 'machine learning',
 'mysql',
 'nam',
 'oracle',
 'php',
 'python',
 'react',
 'rest saturday',
 'ruby',
 'social insurance',
 'spring',
 'sql',
 'typescript',
 'university and above']

In [ ]:
# Build vector skill-level
def build_skill_vector(row):
    text_norm = row["full_text_norm"]
    job_skills = [s.lower() for s in row["required_skills"]]

    vector = []
    for sk in ALL_SKILLS:
        if sk in job_skills:
            vector.append(assign_level(text_norm, sk))
        else:
            vector.append(0)
    return vector

df_test["skill_level_vector"] = df_test.apply(build_skill_vector, axis=1)

In [ ]:
# Decode vector để test
def decode_vector(vec):
    return [ALL_SKILLS[i] for i, v in enumerate(vec) if v == 1]

df_test["strong_skills"] = df_test["skill_level_vector"].apply(decode_vector)

df_test[["title", "required_skills", "strong_skills"]]

                                                title                                    required_skills           strong_skills
0              Staff IAM Engineer, Non-Human Identity  ["[\"aws\", \"azure\", \"ci/cd\", \"devops\", ...                      []
1                                       Data Engineer  ["[\"azure\", \"ci/cd\", \"gcp\", \"git\", \"p...                      []
2                                 DFT Design Engineer                                       ["[\"ai\"]"]                      []
3                              Staff Data Scientist I  ["[\"ai\", \"data science\", \"machine learnin...                      []
4   Senior Security Operations Center (SOC) Analys...                                   ["[\"python\"]"]                      []
5                Senior Software Engineer, Full-Stack                    [python, typescript, react, ai]                [python]
6           Senior/ Principal Android Engineer Kotlin  [java, python, javascript, ruby, php, kotlin, ...               [android]
7   DEVELOPPEUR SENIOR JAVA FULL STACK (Squad Cryp...  ["[\"agile\", \"angular\", \"ci/cd\", \"devops...                      []
8                                 IT Support Engineer  [2 years of experience, college or higher, age...                      []
9   Senior Data Engineer - DataOps Architecture (B...  ["[\"ai\", \"aws\", \"ci/cd\", \"data science\...                      []
10                           Backend Engineer (m/f/d)  ["[\"aws\", \"agile\", \"ci/cd\", \"docker\", ...                      []
11                            Cyber Security Engineer                           ["[\"aws\", \"azure\"]"]                      []
12             Senior Software Developer | Tools4ever           ["[\"angular\", \"devops\", \"scala\"]"]                      []
13                            Senior Backend-udvikler  ["[\"ai\", \"aws\", \"azure\", \"ci/cd\", \"do...                      []
14                                  Software Engineer                              [javascript, angular]                      []
15             Trưởng Bộ PhậnPhát Triển Phần MềmNhúng  [5 years of experience, university and above, ...                      []
16         AI/ML Engineer – XR Software (All levels))                                                 []                      []
17      ERP Supervisor  Dynamics 365 Business Central  [java, python, javascript, ruby, php, spring, ...                      []
18                          Machine Learning Engineer                                                 []                      []
19                 Software Engineer - Infrastructure                                                 []                      []
20                           Senior Software Engineer  ["[\"azure\", \"docker\", \"github\", \"go\", ...                      []
21                   Business Analyst(Fintech Domain)  [3 years of experience, university and above, ...               [finance]
22                         MS Defender/Azure Engineer                                                 []                      []
23                           Senior Android Developer                                    ["[\"agile\"]"]                      []
24                    Full Stack Developer, Associate  ["[\"ai\", \"agile\", \"angular\", \"azure\", ...                      []
25             IT Infrastructure Engineer IV, Network                                                 []                      []
26            Senior Gameplay Cloud Services Engineer                                                 []                      []
27  Automotive ECU SW Developer C programming, Emb...  [java, python, javascript, ruby, php, ci/cd, m...  [agile, ci/cd, devops]
28  Senior Engineer I - Cloud Platforms - Secrets ...                                                 []                      []
29                            Infrastructure Engineer                                                 []                      []

In [ ]:
# Soi chi tiết 1 job
i = 0   # đổi từ 0 → 29 để xem job khác
print("TITLE:", df_test.loc[i, "title"])
print("\nREQUIREMENTS:", df_test.loc[i, "requirements_text"])
print("\nSKILLS:", df_test.loc[i, "required_skills"])
print("STRONG SKILLS:", df_test.loc[i, "strong_skills"])

TITLE: Staff IAM Engineer, Non-Human Identity

REQUIREMENTS: Employee Applicant Privacy Notice
Who we are:
Shape a brighter financial future with us.
Together with our members, we’re changing the way people think about and interact with personal finance.
We’re a next-generation financial services company and national bank using innovative, mobile-first technology to help our millions of members reach their goals. The industry is going through an unprecedented transformation, and we’re at the forefront. We’re proud to come to work every day knowing that what we do has a direct impact on people’s lives, with our core values guiding us every step of the way.
Join us to invest in yourself, your career, and the financial world.
The Role
The Staff IAM Engineer, Non-Human Identity is responsible for securing and managing all non-human identities including service accounts, application identities, machine credentials, APIs, bots, and workloads across on-prem, cloud, and crypto infrastructure. This role ensures that automated and machine-based identities follow the same governance, lifecycle, and least-privilege principles as human users. You will design systems that enable secure authentication, secrets management, and access provisioning for automated services, APIs, and DevOps pipelines. This role directly protects sensitive financial data, crypto custody environments, and transaction systems from privilege misuse, credential leakage, and insider or supply chain threats.
What You’ll Do
Identity Architecture & Engineering
Design, implement, and maintain a Non-Human Identity (NHI) framework governing all service accounts, API tokens, certificates, and machine credentials.
Implement centralized secrets management using tools such as HashiCorp Vault or AWS Secrets Manager,
Build integrations with CI/CD pipelines and cloud services (AWS, GCP, Azure) to enforce automated credential rotation and JIT provisioning.
Define and implement tagging, ownership, and classification models for non-human identities.
Develop scalable onboarding processes for applications, workloads, and bots that require secure authentication.
Lifecycle Management & Governance
Develop automated workflows for creation, rotation, deactivation, and certification of service accounts and API keys.
Partner with developers and DevOps to transition hard-coded credentials to secure vaults.
Establish policies for key rotation frequency, credential expiration, and certificate renewal.
Integrate NHI lifecycle into IAM governance tools (Okta).
Support quarterly access reviews and certification campaigns for non-human identities.
Automation & Integration
Build automation using APIs, Python, PowerShell, or Terraform to manage credentials and monitor access.
Integrate non-human identity telemetry into SIEM/SOAR platforms for anomaly detection.
Implement visibility dashboards to track total NHI inventory, owners, last use, and compliance status.
Deploy Just-in-Time (JIT) credential provisioning for ephemeral workloads and containers (Kubernetes, Lambda, ECS, etc.).
Security & Risk Management
Enforce least privilege and zero-trust principles for machine access.
Monitor for unused or excessive service accounts and remediate over-permissioned credentials.
Support incident response teams with forensics on compromised API keys or tokens.
Define detection logic for credential misuse or non-standard access patterns.
Partner with Application Security to integrate secure NHI handling into SDLC.
Compliance & Audit
Maintain audit trails for credential issuance, usage, and rotation events.
Produce compliance reports for SOX, SOC 2, PCI DSS, FFIEC, and crypto-custody audits.
Collaborate with internal audit and compliance teams to validate NHI control effectiveness.
Document architecture, data flows, SOPs, and exception processes for NHI management.
Innovation & Continuous Improvement
Evaluate emerging NHI management solutions (e.g., SPIFFE/SPIRE, workload identity federation, cloud-native secrets stores).
Lead proof-of-concepts to modernize credentialless or short-lived identity methods.
Advocate for security automation and the reduction of static credentials across the enterprise.
What You’ll Need
Education & Experience
Bachelor’s degree in Computer Science, Cybersecurity, or related discipline.
3–6 years of experience in IAM, DevSecOps, or Security Engineering roles.
Hands-on experience with non-human identity or secrets management tools
Familiarity with cloud IAM concepts (AWS IAM Roles, Azure Managed Identities, GCP Service Accounts).
Experience integrating IAM or secrets systems with CI/CD pipelines and DevOps tools.
Technical Skills
Proficiency in automation and scripting (Python, PowerShell, or Bash).
Strong understanding of authentication standards (OIDC, OAuth 2.0, SAML, JWT).
Knowledge of API security, key rotation policies, and service-to-service authentication.
Familiarity with container and workload identities (Kubernetes, ECS, Lambda).
Understanding of Zero Trust, machine identity, and certificate lifecycle management.
Preferred Certifications
HashiCorp Certified Vault Associate
AWS Certified Security – Specialty
Okta Certified Professional or Administrator
(ISC)² Certified Identity and Access Manager (CIAM) or CISSP
Compensation And Benefits
The base pay range for this role is listed below. Final base pay offer will be determined based on individual factors such as the candidate’s experience, skills, and location.
To view all of our comprehensive and competitive benefits, visit our
Benefits at SoFi
page!
SoFi provides equal employment opportunities (EEO) to all employees and applicants for employment without regard to race, color, religion (including religious dress and grooming practices), sex (including pregnancy, childbirth and related medical conditions, breastfeeding, and conditions related to breastfeeding), gender, gender identity, gender expression, national origin, ancestry, age (40 or over), physical or medical disability, medical condition, marital status, registered domestic partner status, sexual orientation, genetic information, military and/or veteran status, or any other basis prohibited by applicable state or federal law.
The Company hires the best qualified candidate for the job, without regard to protected characteristics.
Pursuant to the San Francisco Fair Chance Ordinance, we will consider for employment qualified applicants with arrest and conviction records.
New York applicants: Notice of Employee Rights
SoFi is committed to an inclusive culture. As part of this commitment, SoFi offers reasonable accommodations to candidates with physical or mental disabilities. If you need accommodations to participate in the job application or interview process, please let your recruiter know or email accommodations@sofi.com.
Due to insurance coverage issues, we are unable to accommodate remote work from Hawaii or Alaska at this time.
Internal Employees
If you are a current employee, do not apply here - please navigate to our Internal Job Board in Greenhouse to apply to our open roles.

SKILLS: ['"[\\"aws\\"', '\\"azure\\"', '\\"ci/cd\\"', '\\"devops\\"', '\\"gcp\\"', '\\"kubernetes\\"', '\\"python\\"]"']
STRONG SKILLS: []